### ISSUE TITLE
IPv4 fallback

### ISSUE THREAD

**Issue by UnderSampled** [bfabiszewski/ulogger-android#100]
I am on a network that has ulogger attempting to connect through IPv6, while that connection cannot be made for one reason or another. I am, however, able to view the webpage of the server I am connecting to, as my browser falls back to IPv4. Is there a way to do something similar in the mobile client?

**Comment by bfabiszewski** [comment]
Documentation for HttpURLConnection says that "this class includes transparent support for IPv6. For hosts with both IPv4 and IPv6 addresses, it will attempt to connect to each of a host's addresses until a connection is established."
Hard to tell why it fails in your case. It may be difficult for me to reproduce it.
When I find some time I will try to simulate similar scenario and check for possible problems.

**Comment by bfabiszewski** [comment]
What is the error message?
What is your Android version?

**Comment by UnderSampled** [comment]
I tried starting a new track, since the error didn't change even with different networks, and that cleared it so I cannot show you. It basically said "cannot connect to (my domain URL) at (server ipv6). Now it says '"upload started" and does nothing (no error l, but stays behind.)

I am on Android 11.
