### ISSUE TITLE
Feature Request - Open recorded gps position in another app

### ISSUE THREAD

**Issue by khlsvr** [bfabiszewski/ulogger-android#101]
Looking for a way to improve the workflow to view the recorder track or just one track point (not current location) on a map offline without the server synchronization setup etc. Currently I would need to save it to a file, then open another app and load it there

Could there be a hyperlink of position and when tapped, would prompt to open it in another app, and I could then choose a map app for opening it? Map apps can easily show me my current location by default when gps is enabled anyway, but if I wanted to see the path of the track or another track point earlier in the track I'm not sure what would be the good way to implement that.

Why I (and maybe some other users) would want this instead of just falling back using the tracking directly in another map app is that let's say that I want to keep tracking me 24/7, but then very spontaneously once a week or whatever check the recent track quickly, I could tap a button in ulogger that would create this current track or track point of it (from track point history I expand from details maybe) on the fly and open it in the map app of my choice. This way I wouldn't need to be running a resource hungry map software, yet I could open my track or track point on a map based on timestamp conveniently on the fly whenever I want by just running ulogger 24/7.  I think this kind of feature would not need a lot of code, and the app would stay small like it is now, yet it would enable the above mentioned extra convience by tieing a map UI to the app seamlessly.

**Comment by bfabiszewski** [comment]
My idea for this logger is to keep client application as simple as possible. I use it only to log track points and send it to server. On the server I can see any point in track history.

You mention possibility of viewing recent tracks or positions. It wouldn't be so simple to implement it in client as recent tracks are not stored in client application (only current track) and there is no interface for selecting individual points on current track. 
Generally µlogger is not well suited for 24/7 logging. I focus on shorter events tracking and client's role is to save positions with basic UI and minimum footprint on device resources.

**Comment by khlsvr** [comment]
Because of the absence of interface for log viewing it's not well suited for 24/7 logging, or why do you think it's not well suited? Even as it is, I still think it has served well, and I choose it over another app, because most of the time for me it's just logging and then only rare occasion I go check the logs. What do you think what would suit this use case better?

**Comment by bfabiszewski** [comment]
I meant the server viewer is not suited for very long tracks.
The client part just doesn't care as long as there is space on the device.
If you export to GPX and then use some other tool to view it, it will work fine.
