### ISSUE TITLE
Feature request - Batch upload

### ISSUE THREAD

**Issue by sinus-x** [bfabiszewski/ulogger-android#105]
When the data is logged offline and the "Upload" button is pressed, the positions are sent one by one. Would it be possible to use some kind of batch upload (JSON list), so it would get sent faster? This is both server- and client-side request, I wasn't sure where it should be filed.

**Comment by bfabiszewski** [comment]
Are you uploading very large tracks? 
The positions are sent one by one, but it usually doesn't take long anyway.

**Comment by sinus-x** [comment]
One of my last tracks had nearly 3000 positions and it took *a while* to upload. It managed to transfer the data in a couple of minutes, but it felt ineffective when I was watching the upload go one by one.
