### ISSUE TITLE
Cannot upload to server hosted as TOR hidden service.

### ISSUE THREAD

**Issue by jw96** [bfabiszewski/ulogger-android#106]
I have my own server hosted as tor hidden service and I can't upload tracks to it.
Synchronization says: "Unknown host"
In orbot µlogger is listed in "Tor-Enabled Apps" (like Fennec which is working with TOR this way.)
Orbot HTTP and SOCKS5 proxy is working (DAVx5 | Telegram) either.

**Comment by bfabiszewski** [comment]
Never used such setup.
I'll have to try to replicate it

**Comment by jw96** [comment]
Can give you user:password and server address in PM, how can I contact you?

**Comment by bfabiszewski** [comment]
Great, please send me the data by email. My address is on [my website](https://www.fabiszewski.net/).

**Comment by jw96** [comment]
Sent

**Comment by bfabiszewski** [comment]
It seems I have just successfully sent a position to your onion service. Please check.

In orbot I just enabled VPN mode and added µlogger to Tor Enabled Apps.

**Comment by jw96** [comment]
I can't do that on my device trough app :c

**Comment by bfabiszewski** [comment]
Must be something with your setup.
I have same error when I have VPN mode disabled in orbot.

**Comment by jw96** [comment]
Okay, it's working now.

I have used orbot beta version from PlayStore, and used one country as a exit node. installed "normal" version and ticked "Global" option. I also deactivated private DNS in android network settings. Thanks for testing server btw.

**Comment by jw96** [comment]
And this also resolved almost identical problem with app Gitnex, thanks a ton. 


https://codeberg.org/gitnex/GitNex/issues/802

**Comment by bfabiszewski** [comment]
Glad to help
