### ISSUE TITLE
no more background sync

### ISSUE THREAD

**Issue by Fraifrai** [bfabiszewski/ulogger-android#107]
Hi,

Since I upgraded from lineageOS 17 to 18 the app does not upload positions in background. When I unlock the phone I can see the unuploaded positions countdown moving to zero.

Thx in advance

**Comment by bfabiszewski** [comment]
I already fixed [similar issues](https://github.com/bfabiszewski/ulogger-android/issues/95) with Android 11 and users reported it worked fine. Make sure you have given all necessary permissions after upgrade. Also disable any battery optimizations for the app. Make sure you use latest version of the app. 
If it still fails I will dig deeper.

**Comment by Fraifrai** [comment]
Indeed, it was the battery saver....
