### ISSUE TITLE
exporting location data directly

### ISSUE THREAD

**Issue by fadelm0** [bfabiszewski/ulogger-android#11]
Is there a way to export the location data to use with other applications?

Currently you have to go through the server app to then export the data. I understand they're meant to work together, but for someone who just cares about the data and the features of the android app, it would be more convenient to just get the data without going through the hassle of hosting the web app.

**Comment by bfabiszewski** [comment]
Hey!
Exporting to GPX format was implemented in [version 1.3](https://github.com/bfabiszewski/ulogger-android/releases/tag/1.3).
I hope this release will soon be available on f-droid.
