### ISSUE TITLE
Synchronization permanently hangs if out of internet range for a long time

### ISSUE THREAD

**Issue by petaded** [bfabiszewski/ulogger-android#113]
## Behaviour of the program
The app never syncs data points after spending a long amount of time out of internet range with live sync turned on even when you return to internet. We had the error "Connection error: failed to connect to XXXXXX/XXXX (port 443) from /XXXXXX (port 38948) after 30000ms: isConnected failed: ETIMEDOUT (Connection timed out)." displayed in app, note the XXXX is my webserver domain and ip.

Once we had returned home and connected to wifi and could reach the server in the browser. The app never synced the positions (was 227 behind). I tried pressing the Upload button however that didn't do anything. It appeared like the upload thread had locked up. My friend had exactly the same problem ( went on a different walk also mostly out of network range ).

Note: we wanted live sync on as at this was a walk up a hill and we would have network at some points during the walk, so I expected it to upload positions as and when network was available. Also my server/app setup is working fine for any walk within network range and if only out of network for a short period of time it does recover and carry on uploading.

Things I tried to get it to sync:
  1. waiting over 10 mins
  1. closing app and opening it - pressing upload
  2. closing app, clearing cache from android settings, opening and then pressing upload
The only solution that allowed the track to be uploaded was restarting my phone - after restart and opening the app, pressing upload it immediately started uploading the positions.

## To Reproduce
Please add all steps to reproduce the behaviour:

    Have live sync turned on
    walk for 2 hours out of internet range (and had over 100 location points to sync)
    return to internet range

## Environment Information:
    Android version: 11 
    ulogger version: 3.5
Also reproduced on:

    Android version: 10
    ulogger version: 3.5

**Comment by MalakymR** [comment]
We've been getting similar on 3 devices, though force stopping the app and starting again works.

I did think it was to do with being on an intermittent signal, though now you say this its likely to do with length of time.

**Comment by bfabiszewski** [comment]
Thanks for the report. 
I don't experience such issues on my device which is running some ancient Android version. So I assume it must be related to versions 10 and above.
I will try to do some testing on another device to pinpoint the problem.

**Comment by petaded** [comment]
Some updates,

1. the force stop suggested by MalakymR does indeed work for getting it to resync. - much better than restarting my phone so thanks for this
2. I've managed to find an easier way to reproduce the issue:

Steps to reproduce (on my android 11 phone):
1. Create a new track
2. have live sync set to ON
3. turn off wifi and mobile data
4. start tracking
5. register one position (e.g. where you currently are)
6. press "upload" repeatedly and wait about 10 mins
7. turn wifi back on, we have hit the problem (the single position behind will never sync)

If you don't spam press upload it will re-sync when you turn wifi back on (at least if I only wait an hour and only have the single location point) - so it seems to be something to do with the number of times it tries to upload when we don't have data.

e.g. You can reproduce either by:
1. getting a large number of location points while having no internet
2. spamming the upload button while having no internet - this one doesn't require as much time.

Hope this helps debug the issue

**Comment by petaded** [comment]
Just tested on an android 6.0.1 phone and can confirm that it had no issues, so it is indeed a problem with newer android versions.

Also another difference between android 6.0.1 and 11 was that every time I pressed upload on the android 6 phone it flashed "upload started" and also had the error messages flashing as well. Where as on android 11, I get a single "upload started" message which doesn't disappear and reappear on each upload click, it just stays there until it stop pressing upload and I have no error messages popping up.

Also I missed this from my previous message but following the steps to produce the error on my 11 phone didnt show any error messages at any point, even though I hit the syncing issue.

Thanks for your time investigating this issue @bfabiszewski.

**Comment by petaded** [comment]
@bfabiszewski I've discovered the issue. its the alarm.

What happens is the alarm starts up a WebServiceSync however nothing is enqueued so it doesnt doSync and more importantly it is also never destroyed. After the alarm has triggered once, WebSyncService will never call handleWork again regardless of how many you things you enqueue.
You can see this in the debug log, here is what happens on alarm triggering
```
11-21 16:20:47.960 25859 25859 I WebSyncService: [websync create]
11-21 16:20:47.965 25859 25859 I DbAccess: [+openCount = 5]
11-21 16:20:47.965 25859 25859 I WebSyncService: [websync create finished]
```
Thats all thats printed, As you can see the WebSyncService is created but never does doSync and it never destroys itself.
Compare that to a normal trigger through upload
```
11-21 14:51:01.472 21927 21927 I WebSyncService: [websync create]
11-21 14:51:01.473 21927 21927 I DbAccess: [+openCount = 5]
11-21 14:51:01.479 21927 22201 I WebSyncService: [websync start]
11-21 14:51:01.480 21927 22201 I WebSyncService: [websync cancel alarm]
11-21 14:51:01.481 21927 22201 I WebSyncService: [authorize]
11-21 14:51:01.481 21927 22201 I WebSyncService: [postForm: https://ulogger.zikl.co.uk/client/index.php : {pass=wed2165p, action=auth, user=jon}, image=null]
11-21 14:51:01.489 21927 22201 I WebSyncService: [websync retry: Unknown host: Unable to resolve host "ulogger.zikl.co.uk": No address associated with hostname]
11-21 14:51:01.492 21927 22201 I WebSyncService: [websync set alarm]
11-21 14:51:01.493 21927 21927 I MainFragment: [broadcast received Intent { act=net.fabiszewski.ulogger.broadcast.sync_failed flg=0x10 (has extras) }]
11-21 14:51:01.493 21927 21927 I DbAccess: [+openCount = 6]
11-21 14:51:01.495 21927 21927 I DbAccess: [-openCount = 5]
11-21 14:51:01.496 21927 21927 I MainFragment: [setSyncLed 2]
11-21 14:51:01.497 21927 21927 I MainFragment: [setSyncLed 2]
11-21 14:51:01.508 21927 21927 I WebSyncService: [websync stop]
11-21 14:51:01.508 21927 21927 I DbAccess: [-openCount = 4]
```

Apparently this is an issue from Android 8.0 onwards. I have got the workaround from this stackoverflow 
https://stackoverflow.com/questions/46675242/issue-moving-from-intentservice-to-jobintentservice-for-android-o

have done the fix here: https://github.com/petaded/ulogger-android/tree/dev/petaded/fix_sync_hanging
This fixes the issue for me on android 11. However it doesn't work on older android ( tried on my android 6 phone )

**Comment by bfabiszewski** [comment]
Great job, thanks! I understand that the problem may be caused by websync service running as background job. Maybe the simple solution would be to change it to foreground service, which I should have done long time ago.
I will look into it. 
Strange thing is that I can't reproduce it on Android 10 device. Do you have battery optimization disabled for µlogger?

**Comment by petaded** [comment]
Under settings -> Battery i'm in "Device Performance profile: Balanced" which must be the default since i haven't changed anything.
If i look at ulogger; settings -> apps -> ulogger -> battery its on "Optimising battery use" so I guess i don't have it disabled which again must be the default as I haven't changed anything.

I have just tested with and without battery optimisation it made no difference, I hit the problem either way.
Here is a basically full log from logcat from one of my test runs and how im doing the testing:


## inital location pickup
```
11-21 19:01:03.845 30475 30680 I LoggerService: [location changed: Location[gps 51.462661,-2.104820 hAcc=14 et=+7d2h46m42s642ms alt=108.12994384765625 vel=0.0 vAcc=6 sAcc=1 bAcc=??? {Bundle[mParcelledData.dataSize=96]}]]
11-21 19:01:03.846 30475 30680 I LocationHelper: [hasRequiredAccuracy: true]
11-21 19:01:03.846 30475 30680 I LocationHelper: [isNetwork: false]
11-21 19:01:03.846 30475 30680 I DbAccess: [+openCount = 5]
11-21 19:01:03.846 30475 30680 I DbAccess: [writeLocation]
11-21 19:01:03.866 30475 30680 I DbAccess: [-openCount = 4]
11-21 19:01:03.868 30475 30680 I LocationHelper: [isLiveSync: true]
11-21 19:01:03.879 30475 30475 I MainFragment: [broadcast received Intent { act=net.fabiszewski.ulogger.broadcast.location_updated flg=0x10 }]
11-21 19:01:03.883 30475 30475 I MainFragment: [setLocLed 1]
11-21 19:01:03.898 30475 30475 I WebSyncService: [websync create]
11-21 19:01:03.899 30475 30475 I DbAccess: [+openCount = 5]
11-21 19:01:03.913 30475 30662 I WebSyncService: [websync start]
11-21 19:01:03.914 30475 30662 I WebSyncService: [authorize]
11-21 19:01:03.914 30475 30662 I WebSyncService: [postForm: https://ulogger.foo.co.uk/client/index.php : {pass=foo, action=auth, user=bob}, image=null]
11-21 19:01:03.935 30475 30662 I WebSyncService: [websync retry: Unknown host: Unable to resolve host "ulogger.foo.co.uk": No address associated with hostname]
11-21 19:01:03.957 30475 30662 I WebSyncService: [websync set alarm]
11-21 19:01:03.960 30475 30475 I MainFragment: [broadcast received Intent { act=net.fabiszewski.ulogger.broadcast.sync_failed flg=0x10 (has extras) }]
11-21 19:01:03.960 30475 30475 I DbAccess: [+openCount = 6]
11-21 19:01:03.963 30475 30475 I DbAccess: [-openCount = 5]
11-21 19:01:03.991 30475 30475 I MainFragment: [setSyncLed 3]
11-21 19:01:03.992 30475 30475 I MainFragment: [setSyncLed 2]
11-21 19:01:03.995 30475 30475 I WebSyncService: [websync stop]
11-21 19:01:03.995 30475 30475 I DbAccess: [-openCount = 4]
```
## snip 30s to alarm trigger (notice no websync stop or actual syncing) 
```
11-21 19:00:57.893     0     0 W healthd : battery l=99 v=4411 t=22.8 h=2 st=2 c=246734 fc=3056000 cc=22 chg=u
11-21 19:01:16.399  3969  3969 D GmsGcmTrigger: Ignoring Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }: network is offline, scheduling new attempt.
11-21 19:01:16.406  3969  3969 D GmsGcmMcsSvc: Scheduling reconnect in 50 seconds...
11-21 19:01:33.972 30475 30475 I WebSyncService: [websync create]
11-21 19:01:33.975 30475 30475 I DbAccess: [+openCount = 5]
11-21 19:00:57.918     0     0 W healthd : battery l=99 v=4411 t=22.8 h=2 st=2 c=246734 fc=3056000 cc=22 chg=u
11-21 19:01:33.999     0     0 W healthd : battery l=99 v=4411 t=22.8 h=2 st=2 c=241394 fc=3056000 cc=22 chg=u
11-21 19:02:00.040  1809  1809 D KeyguardClockSwitch: Updating clock: 19:02
11-21 19:02:06.442  3969  3969 D GmsGcmTrigger: Ignoring Intent { act=org.microg.gms.gcm.mcs.RECONNECT flg=0x14 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }: network is offline, scheduling new attempt.
11-21 19:02:06.448  3969  3969 D GmsGcmMcsSvc: Scheduling reconnect in 120 seconds...
```
## pressing upload after alarm trigger (notice no websync stop) 
```
11-21 19:02:11.111 30475 30475 I DbAccess: [+openCount = 6]
11-21 19:02:11.115 30475 30475 I DbAccess: [-openCount = 5]
11-21 19:02:11.130 30475 30662 I WebSyncService: [websync start]
11-21 19:02:11.130 30475 30662 I WebSyncService: [websync cancel alarm]
11-21 19:02:11.131 30475 30662 I WebSyncService: [authorize]
11-21 19:02:11.132 30475 30662 I WebSyncService: [postForm: https://ulogger.foo.co.uk/client/index.php : {pass=foo, action=auth, user=bob}, image=null]
11-21 19:02:11.141 30475 30662 I WebSyncService: [websync retry: Unknown host: Unable to resolve host "ulogger.foo.co.uk": No address associated with hostname]
11-21 19:02:11.143 30475 30662 I WebSyncService: [websync set alarm]
11-21 19:02:11.145 30475 30475 I MainFragment: [broadcast received Intent { act=net.fabiszewski.ulogger.broadcast.sync_failed flg=0x10 (has extras) }]
11-21 19:02:11.145 30475 30475 I DbAccess: [+openCount = 6]
11-21 19:02:11.147 30475 30475 I DbAccess: [-openCount = 5]
11-21 19:02:11.148 30475 30475 I MainFragment: [setSyncLed 2]
```
## second press upload  afterwards
```
11-21 19:03:01.689 30475 30475 I DbAccess: [+openCount = 6]
11-21 19:03:01.692 30475 30475 I DbAccess: [-openCount = 5]
```
## third press upload  afterwards (all uploading at this point does nothing)
```
11-21 19:03:02.564 30475 30475 I DbAccess: [+openCount = 6]
11-21 19:03:02.566 30475 30475 I DbAccess: [-openCount = 5] 
````
The way im doing the above testing:

building debug apk (with Log.d changed to Log.i so they would show up), copying to my connected phone- then install.
Watching on `adb logcat` on the computer
opening ulogger-dev, setup live sync and turn wifi + internet off, start a track and wait for first position, then alarm to trigger and then pressing upload twice.

In the code I had the alarm timer set to 30 seconds so i didn't have to wait long for the issue to appear and I could see when it happened in the log without having to turn the phones internet back on. After the alarm triggered, the upload would be broken after the second press of upload ( as shown in output above )

**Comment by bfabiszewski** [comment]
OK.  Still the battery optimization must be disabled for µlogger to work in background. Otherwise the OS may kill the background process. It also affects location listener.
As the JobIntentService is deprecated anyway I will rewrite first. Then we will see if the issue persists.

**Comment by bfabiszewski** [comment]
I pushed a [branch](https://github.com/bfabiszewski/ulogger-android/tree/android-s) in which I replace JobIntentService with foreground Service. Could you please check whether it fixes the problem?
Bear in mind that this in work in progress, so some other issues may come up. But it would be nice to know if synchronization problem is fixed before going any further.

**Comment by petaded** [comment]
Can confirm your branch does fix the issue for me. (only tested on my android 11 phone)

The alarm reliably triggers each time (and attempts to do the upload) then restarts the alarm.
Also the manual upload button is working after the alarm triggers.

Just to note one of the side affects of your change is that I get a "ulogger-dev is running" popup each time the alarm triggers / upload is attempted - though this is not a problem.

Once again thank you for investigating this :)

**Comment by bfabiszewski** [comment]
Great, thanks! Your investigation and testing helped me a lot.
I noticed the annoying notifications, I will see how to handle that.

**Comment by Dan-Q** [comment]
As somebody who's affected by this several times a week (on Android 10 and 11, not seen on 12 yet) I'm excited to see that progress is being made on this. Wish I were an Android developer so I could be more help than just cheering from the sidelines!

**Comment by Quppa** [comment]
I have a similar issue where I have to force stop the app to resume syncing after my server goes offline temporarily or changes IP address. Looking forward to seeing this fix land.
