### ISSUE TITLE
http links in the About window don't work

### ISSUE THREAD

**Issue by chipechop** [bfabiszewski/ulogger-android#114]
Hi, I am not a developer, but I noticed that the links in the about window don't work (they're green and underlined, but don't work).

Could it be that a backslash is missing somewhere, before the " characters, around the URLs?

CODE AS IT IS TODAY AND DOESN'T WORK, IN: https://github.com/bfabiszewski/ulogger-android/blob/master/app/src/main/res/layout/about.xml

    <string name="about_description">Simple location logger with support for live tracking and position uploading to own <xliff:g id="server_link_open"><![CDATA[<a href="https://github.com/bfabiszewski/ulogger-server">]]></xliff:g>μlogger server<xliff:g id="server_link_close"><![CDATA[</a>]]></xliff:g>.</string>
    <string name="about_description2">For more information and help please see <xliff:g id="app_link_open"><![CDATA[<a href="https://github.com/bfabiszewski/ulogger-android">]]></xliff:g>μlogger homepage<xliff:g id="app_link_close"><![CDATA[</a>]]></xliff:g>.</string>

**Comment by bfabiszewski** [comment]
Thanks for finding this bug!
I think it is another problem, not a missing backslash.
