### ISSUE TITLE
Multiple user on a map

### ISSUE THREAD

**Issue by jonifishi** [bfabiszewski/ulogger-android#115]
I wonder if it is possible to display all users coordinate on the map

**Comment by bfabiszewski** [comment]
Sorry, didn't notice this earlier.
This question rather belongs to [μlogger server](https://github.com/bfabiszewski/ulogger-server).
Anyway it is possible to display all users coordinates, but only when showing latest position of each user. 
When you check "latest position" checkbox, you can select "all users" from User dropdown.
