### ISSUE TITLE
Not fetching location on Android 11 (Lineage 18)

### ISSUE THREAD

**Issue by jayfan0** [bfabiszewski/ulogger-android#117]
Hello,
First of all, thanks for the app!

When I turn on the tracking there is no location icon in the status bar and the location is never fetched. I have tried other location apps like GPSLogger and GPSTest and as soon as location is requested the status bar icon shows up and location is fetched.

If I run those above apps in parallel with uLogger then it works. It used to work when I was on android 10 (google free lineage 17). Since updating to lineage 18 (android 11) uLogger no longer fetches location by itself but seems to instead use locations fetched by other apps.

Battery optimization for uLogger is off and location is allowed all the time, providers are set to network and gps

**Comment by bfabiszewski** [comment]
This is strange. I've been using µlogger on various custom ROMs without problems. Currently I have it installed on degoogled ROMs (with MicroG) with Android 12 and 13.
Maybe try to reinstall the app if you didn't after system update.

On the other hand there are reports of issues with some applications using GPS on Lineage 18, but I am not sure what the problem is, see for example:
https://gitlab.com/LineageOS/issues/android/-/issues/3436
https://forum.xda-developers.com/t/gps-does-not-work-on-lineageos-18-1.4261353/page-2#post-85627461

I don't know how to reproduce it. Maybe try to see the system logs for any problems while using µlogger.

**Comment by jayfan0** [comment]
So I just did a complete wipe of my phone and re-flashed recovery, installed lineage 18.1 again, and installed ulogger and ulogger-dev, both showed the same issue of not initiating the location service. GPSlogger, osm, organic maps all work immediately. ill keep digging around.

silly question but where might i find the system logs...? Are they the same as the logs on android studio

**Comment by jayfan0** [comment]
Just downgraded to 17.1...same situation... this is so bizarre!

**Comment by bfabiszewski** [comment]
Really strange.
By system logs I meant the logcat log, the one you see in Android Studio. 
I understand you have built development version of µlogger. That's great, because it enables debug log.
Could you post ulogger-dev logs showing what the application does after turning on location tracking?

**Comment by bfabiszewski** [comment]
Are you testing with the same µlogger version that used to work on Lineage 17.1?
What device do you use?

**Comment by jayfan0** [comment]
So, suddenly it sprung to life as I was out today. Im using a OnePlus 3 with microg for lineage. It seems while the gps icon does not show for ulogger, the app instead gets it location from mozilla unifiednlp. This seems different to gpslogger.
I'll try upgrading to lineage 18 again and retest everything before either posting logs or closing the issue.
I have read on some sites that microg may be the culprit for some location issues.

bare with me while I do this as its my main phone I keep resetting and flashing.... ha

**Comment by bfabiszewski** [comment]
Don't worry, it would be interesting to understand this behavior.

I remember some other users also reported problems with OnePlus devices.

Also check the logs. If you were testing only with network provider, it is possible that µlogger didn't record position because it didn't meet accuracy criteria.

**Comment by jayfan0** [comment]
Okay so I got to try it outside today and it worked pretty well so I cant fault it - I'll close the issue.

I have no idea what it could have been. Part of me is thinking maybe my MicroG/ unifiednlp wasnt set up properly initially because my banking apps didnt work either (microg safetynet failed) 

When I downgraded to lineage 17.1 and then back to 18.1, setting everything up properly was just as much of a priority as the logging apps since its my main phone so maybe I gave it more time and attention to sort out than last time

For completion/ reference I'll write up the "fix" anyway:
On installing lineage with microg, go to microG settings > location modules > turn on location services (i think microg ships with Mozilla Location Services by default but there are others you can download).
Ensure logging accuraty, and minimum times are set generously.

Its worth noting though it still seems as though uLogger cant fetch the location by itself but instead relies on unifiednlp (unlp) to get the location for the app. When the little location icon pops up in the status bar its almost always "Mozilla UnifiedNlp Backend", however uLogger does _very occasionally_ appear there. probably to grab the network location from UNLP. It could be that gpslogger and gpstest have something that keeps gps alive all the time while it looks for satellites as they show up under that icon as expected. If i set ulogger to gps only it doesnt appear (nor does unlp) so maybe theres something in the code that actively triggers gps hardware?

**Comment by jayfan0** [comment]
It makes sense to use that approach for battery conservation. I'm also glad to hear it doesn't use Google Play Services for those of us who have decided to "degoogle". 
It could be a vendor (OnePlus ) issue but it might also be a statistic because from what I can see OnePlus devices in general are quite well supported for custom roms. Maybe there are more issues because there are more people using them this way? Unless you mean OP devices in general have issues without custom roms

> Regarding microG usually no Nlp modules are included by default. But some installers may automatically supply them.

I stand corrected, it might be the image i flashed bundled it this time, in which case im inclined to think it was a config issue on my end initially.
Unfortunately I cant check the recorded track as I'm logging to my nextcloud-phonetrack instance for now which I dont think shows that information. I do wonder though if gps is more accurate but much slower to get, wouldnt UNLP give the location most of the time as it would be the first to respond to the location request (accuracy criteria aside), unless gps already has a recent fix?

> You mean the location icon does not show up or µlogger icon?
The location icon. uLogger icon is always showing when logging is active. When the location icon pops up I click it and it shows me what apps are using location services. often Mozilla NLP is there as the user but not ulogger (very occasionally does though).

> I understand that despite no icon, the location is still fetched from GPS in this case, isn't it?
I honesty cant say as i usually set network + gps. I'll have to double check when setting to gps only mode to confirm. I'll keep experimenting with settings when im out and about and might set up ulogger server for that gps/network info

**Comment by bfabiszewski** [comment]
Thanks!

With the OP devices it was just my theory. I never used any of those myself, but remember a few reports where OnePlus appeared in context of LineageOS (also reported outside of Github). I didn't have any similar problems myself with other devices. May be pure statistics as well.

> I do wonder though if gps is more accurate but much slower to get, wouldnt UNLP give the location most of the time as it would be the first to respond to the location request (accuracy criteria aside), unless gps already has a recent fix?

The application gives priority to GPS location. It will skip network location if it have successfully received GPS position within a short period.

**Comment by jayfan0** [comment]
Ah that makes sense now from what I saw on the gpx file. Good to know!
Anyway its all working. I'll play around some more with settings, accuracy etc and report if I find anything, but otherwise thanks for the amazing app and the quick responses :)

**Comment by bfabiszewski** [comment]
Thanks!
