### ISSUE TITLE
Tracking doesn't resume after reboot

### ISSUE THREAD

**Issue by Terrance** [bfabiszewski/ulogger-android#118]
After a reboot, μlogger's persistent notification will reappear with a few minutes' delay, and opening the app shows the tracking slider enabled, but the location stays in yellow state and doesn't seem to record any data points until I disable and re-enable tracking.

I'm on a OnePlus Nord CE running Android 12 (OxygenOS 12.1), I've disabled all the OS optimisations I'm aware of (namely "allow background activity" and "allow auto-launch"), and the app is set to start on boot.

**Comment by bfabiszewski** [comment]
Location permission must be set to "Allow all the time" for automated use.
It is also necessary to disable battery optimizations in this case.
See https://github.com/bfabiszewski/ulogger-android/issues/116

**Comment by Terrance** [comment]
> Location permission must be set to "Allow all the time" for automated use.

I'm pretty sure I'd set the location permission to "Allow all the time" when I first switched to this phone, but it seems to have dropped to "Allow only while using the app" at some point.  Not sure when that happened, maybe from the recent Android 12 update.  I've upped it to "Allow all the time" again and turned off removing unused permissions; after a reboot it seems to have logged an initial point so hopefully we're good now -- thanks for the hint.

Interestingly it's been working fine otherwise like this, after toggling the tracking off and on again once (even if the app is swiped away etc. it's not failed to track once it's got going, though opening the app isn't enough to start it even with the persistent notification).

>  It is also necessary to disable battery optimizations in this case.

OxygenOS' battery optimisation setting appears to be the "allow background activity" one, as that's where it sends you when you pick an app from the battery usage screen or if an app tries to open its own optimisation settings screen.

**Comment by bfabiszewski** [comment]
Thanks for the update, glad it works!

> Interestingly it's been working fine otherwise like this, after toggling the tracking off and on again once (even if the app is swiped away etc. it's not failed to track once it's got going, though opening the app isn't enough to start it even with the persistent notification).

"Allow all the time" option is needed when requesting location without user interaction. When you restart tracking from user gui it will work without it.
