### ISSUE TITLE
Sudden HTTP Error code 500 with Nextcloud/PhoneTracker

### ISSUE THREAD

**Issue by FreeJulianAssange** [bfabiszewski/ulogger-android#123]
Apologies, I should have checked first!

This bug has been logged already on the Phonetrack's Gitlab page [https://gitlab.com/eneiluj/phonetrack-oc/-/issues/460](url)

-- 

I few weeks back I suddenly encountered HTTP error code 500, with the only change on my phone being an update to Android 13.

My Nextcloud server also updated to version 25.0.3 & I updated the server from PHP7.4 to 8.1, however that update was before the Android 13 update and uLogger was still working at that time.

I was initially thinking it might be the Android 13 update as all my older Android devices were still working fine, however they've also just stopped working today (They were working for at least 3 weeks longer than my Android 13 device) all now get a HTTP 500 error.

Please let me know if I can provide any other details or if I was raise this bug with PhoneTrack?

Nextcloud Error (Censored):
```
[index] Error: Exception: OCA\PhoneTrack\Controller\LogController::logUlogger(): Argument #2 ($lat) must be of type float, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/phonetrack/lib/Controller/LogController.php' line 1988 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

POST /index.php/apps/phonetrack/log/ulogger/SessionToken/USERNAME/client/index.php
from ###.##.29.7 at 2023-02-07T05:07:17+00:00
```

**Comment by bfabiszewski** [comment]
I am not familiar with Nextcloud or Phonetrack. It seems to be a server-side problem.
If you want to rule out the client, try to log position to [µlogger server](https://github.com/bfabiszewski/ulogger-server), eg. demo server

**Comment by FreeJulianAssange** [comment]
Apologies, I should have checked before I posted.

This bug has been logged already on Phonetrack's Gitlab page [https://gitlab.com/eneiluj/phonetrack-oc/-/issues/460](https://github.com/bfabiszewski/ulogger-android/issues/url)

Sorry for posting this.

**Comment by bfabiszewski** [comment]
OK. So I am closing it now. 
Just reopen if you need some help here.
