### ISSUE TITLE
Exception: OCA\PhoneTrack\Controller\LogController::logUlogger(): Argument #2 ($lat) must be of type float, null given

### ISSUE THREAD

**Issue by halunke1050** [bfabiszewski/ulogger-android#124]
Hi,

with latest update of phonetrack-oc v0.7.4 when using ulogger, which worked very well few weeks ago there is now this exception:
`[index] Fehler: Exception: OCA\PhoneTrack\Controller\LogController::logUlogger(): Argument #2 ($lat) must be of type float, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/nextcloud/apps/phonetrack/lib/Controller/LogController.php' line 1988 at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/html/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/html/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/html/nextcloud/index.php line 36
   OC::handleRequest()

POST /nextcloud/index.php/apps/phonetrack/log/ulogger/7f7203a9784ab72be2c6c8aeb8bd3b3f/MeinNam/client/index.php
from 89.204.138.187 at 2023-02-25T20:37:10+00:00`

The attempt of downgrading phonetrack on server side didn't work.

Any hints would be appreciated :)

Update:
Found a workaround with downgrading to v0.7.2 of nextcloud app.
worked like this.

1. disabled and deleted the phonetrack app in admin panel of nextcloud
2. downloaded old version from [https://apps.nextcloud.com/apps/calendar/releases?platform=22#22\](https://apps.nextcloud.com/apps/calendar/releases?platform=22#22%5C)
(i tried cloning the repo and using the code from release tag but this didnt work)

3.extract archive to app directory in nextcloud directory (for apache: /var/www/html/nextcloud/apps/phonetrack
4. chown -R www-data:www-data *
5.refreshing apps view in admin panel of nextcloud
6.enabling phonetrack
7. using with ulogger without problems :)

**Comment by bfabiszewski** [comment]
Thanks for the info, but this is not ulogger problem.
You must report in to phonetrack or nextcloud.
I've never used any of this applications, so I can't help you.
