### ISSUE TITLE
Some Tutorial

### ISSUE THREAD

**Issue by Rgatesss** [bfabiszewski/ulogger-android#13]
Hai, I'm new on programming can you give some tutorial for connecting ulogger server to android ? I have save or install ulogger to my localhost and install ulogger on my android but it doesn't give me anything i'm trying to start and stop the application but still can't detect my location. Can you please help me?

**Comment by bfabiszewski** [comment]
For server part you need a hosting with web server, PHP and MySQL. 
Did you manage to install web application following instructions on [μlogger server page](https://github.com/bfabiszewski/ulogger-server)? Please note that the instructions refer to latest git version.
Did you set up your user account on server?

**Comment by Rgatesss** [comment]
I know what u mean and the server is work in my browser. But can i try  the client with my localhost? Like try it on my IDE/emulator for android client. And can you show me which part of code that showing the sending data from client to server, i mean how it can connect using http or something else .? .thank u

**Comment by bfabiszewski** [comment]
It may work on your local network, but It depends on your network configuration.
Emulator virtual machine and your pc with web server installed must be on the same subnet. In android application you must specify ip address of your local machine with web server running, for example "http://192.168.1.2" (or https, depends on your web server configuration). 
Regarding your question android µlogger app connects to web server using http protocol, just like normal web browser.

**Comment by amadeous** [comment]
> i'm trying to start and stop the application but still can't detect my location

@Rgatesss I had the same problem at first. You have to make sure that you let the application access your localisation (on your phone's settings) and you also have to move and/or wait (walk sth like 50 meters and/or wait ~30 seconds by default) to make the application start recording a location. You can change these default values in the application's settings. :)
Hope that helped !

**Comment by bfabiszewski** [comment]
> i'm trying to start and stop the application but still can't detect my location

Also make sure you are using latest version: 1.3. 
Previous versions had silently failed if permissions were not granted or location providers were disabled.
