### ISSUE TITLE
Server https with certificate autosign... Exception: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by gnuismo** [bfabiszewski/ulogger-android#14]
I see https://developer.android.com/training/articles/security-ssl.html?
It for add to ulogger-android/app/src/main/java/net/fabiszewski/ulogger/WebHelper.java
But I can't see how android app could load '.crt' file. Or it used as string simple.

My idea is use it with raspberry pi as server (I tried letsencrypt.org but not work, then I create autosigned certificate)

Cheers.

**Comment by bfabiszewski** [comment]
You will need to install your CA certificate (the one used to sign generated web server certificate) to Android device. 
I don't recall how to exactly achieve this (I used to do it with older firmwares, but something changed recently). Try this link:
http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets

Otherwise try again with letsencrypt. I use it and it works reliably with recent Androids.

**Comment by hydris** [comment]
Hi,
Thanks for your work, i love your app :-)
I try your app (1.3) with cm13 and no problem with my autosigned certificate. I had previously installed my certificate with CADROID. But, since I have installed Lineageos 14.1 for Oneplus One. But I tried to import my certificate with cadroid, unfortunately, it doesn't work. 
I have not tested version 1.4 yet
![img_20170421_103037](https://cloud.githubusercontent.com/assets/4647185/25269624/cbe2629e-267d-11e7-8699-1c830d6b08c3.jpg)

**Comment by bfabiszewski** [comment]
µlogger uses system certificates, so they must be properly installed.
If it worked in CM, it should also work in Lineageos. Maybe you could get some help from Lineagos support? 
I would be interested to get some feedback from, whether you manage to fix it or not.

**Comment by hydris** [comment]
It strange, because davdroid need cadroid to import self-signed certificate... I tried to get some help from Lineagos support.
Thanx

**Comment by hydris** [comment]
Very strange, all my apps work with my self-signed certificate.
With which version of Android have you tried your app? I'm not a connoisseur, but maybe the Android 7 certificate store has changed place.
Thanx

**Comment by gnuismo** [comment]
Ups...I had not time. Sorry
I worked with it in LineageOS 14.1.
Now, I try it in Android 5.1 and µlogger say error: hostname was not verified. I have installed certificate through 'Security' menu in 'Settings'. I have tried url as domain (freedns) and IP. But I keep on get same error.

could be I use a port different to 443?

Thank you.

**Comment by bfabiszewski** [comment]
@hydris @gnuismo 
I haven't checked it with self-signed certificate yet. I'll have a look at it
Can you connect to your web server with android browser?

**Comment by gnuismo** [comment]
Yes... First time say there are a problem with certificate, then confirm and next time I get web page without error.

**Comment by bfabiszewski** [comment]
Ah, if browser warns about the problem, µlogger will not connect. This is expected behaviour.
I will have to test if it is possible to install ca certificate on android, in such way that self-signed certificates are usable.

**Comment by hydris** [comment]
Hello,
I have the same problem with 1.4 version with my config :
LineageOS 14.1
CAdroid 
self-signed certifcate installed

Thx

**Comment by bfabiszewski** [comment]
I did some tests.
It seems that it is possible to use self-signed certificates with modern Android if they are properly installed.

How I tested:

# Generating test certificates for webserver:
```
$ openssl genrsa -out ca.key 4096
$ openssl req -new -x509 -days 3650 -key ca.key -out ca.crt
$ openssl genrsa -out server.key 4096
$ openssl req -new -key server.key -out server.csr
$ openssl x509 -req -days 3650 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt
```
Web server needs: `server.crt` and `server.key`.

After configuring web server with above files I try to connect with android µlogger and I got error:
`Trust anchor for certification path not found.`
That is expected as the system doesn't know about my certificate authority. So now, I must install my CA certificate: `ca.crt`.

# Installing on Android
I upload the file `ca.crt` to android device, then I go to:
- Settings -> Security -> Install from storage
Choose certificate file, choose whatever name you want when prompted, click ok.

Make sure the certificate is properly installed, go to:
- Settings -> Security -> Trusted credentials -> User
Your CA certificate should be listed in User tab.

No I go back to µlogger, click Upload and it connects without problem.

It should work on Android starting with version 4.0 (which added user storage for certs). For lower versions may be more difficult.
Please check how to do it on LineageOS.

**Comment by miche7** [comment]
Unfortunately, it doesn't work...

**Comment by miche7** [comment]
Unfortunately, it doesn't work...

**Comment by bfabiszewski** [comment]
@miche7 
Please describe all the steps you took, how you generated certificate, how you installed ca certificate, what error message you get, what your system version is etc.

**Comment by miche7** [comment]
LineageOS (lineage-14.1-20170501-nightly-bacon-signed.zip)
Make my own certificate 
`$ openssl genrsa -out ca.key 4096`
`$ openssl req -new -x509 -days 3650 -key ca.key -out ca.crt`
`$ openssl genrsa -out server.key 4096`
`$ openssl req -new -key server.key -out server.csr`
`$ openssl x509 -req -days 3650 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt`
And I put my ca.crt "> Settings -> Security -> Install from storage"

PS : I am hydris -> i have lost my account

**Comment by bfabiszewski** [comment]
@miche7 
- What is the error message?
- Is your certificate listed in Settings -> Security -> Trusted credentials -> User?

**Comment by miche7** [comment]
@bfabiszewski 

- java.security.cert.CertPatchValidatorException: Trust anchor for certification path not found.
- Yes

**Comment by bfabiszewski** [comment]
@miche7 
I can't reproduce your issue. My test were successful.
Maybe it doesn't work with LineageOS?
Or there is something wrong with the certificate? 
Even if you followed my example, you certificate may be invalid. The commands are only example and are based on system defaults that may differ. Certificate common name should of course match your host name (though a mismatch will result in "hostname not verified" error).

If possible check if your setup works with Android.

**Comment by miche7** [comment]
@bfabiszewski 
my hostname is www.mydomain.net
and my certificate have : www.mydomain.net
I think is a problem of LineageOS

**Comment by gnuismo** [comment]
Hello, I get it work in Android 5 ... my error was CN != domain, I believe... but LineageOS 14 (Android 7) I not get success. I don't know cause if LineageOS else version 7 of Android. Because in LineageOS the certificate is correctly installed but µlogger neither internet browser know of it.

Does anyone successfully work on Android 7? Maybe it could be Android has become very strict

**Comment by bfabiszewski** [comment]
Ok. Thanks for the hints. 
You are right. It changed in version 7.
I need to explicitly allow for user certificates in manifest. I will prepare a quick fix.

**Comment by choss38** [comment]
Hi,
I've got the same problem with Lineage OS 14.1.
error: java.security.cert.CertPatchValidatorException: Trust anchor for certification path not found.
Is your certificate listed in Settings -> Security -> Trusted credentials -> User ? No, but it's in Settings -> Security -> user logins (Identifiants de l'utilisateur in french!)

@miche7: how did you do to put the certificate Settings -> Security -> Trusted credentials -> User ?
