### ISSUE TITLE
feature request: export gpx file on device

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#2]
Hi, would you please add (1) a button and (1) a scriptable intent to export all the data fields of the current, non-synced track as a gpx file?

The use case is: completely offline, 24/7, network location tracking. I.e. I'm not using a ulogger server at all. Occasionally, I'd like to view the track in Osmand, or run scripts to figure out when I'm at work etc. (I'm so glad there's finally a location tracker that does not insist on GPS.)

Why that? Offline -> privacy (and easier firewall config). 24/7 -> quantified self. Network location -> battery drain, indoors a lot. No ulogger server -> questions like "look where I took the kids" or "which way is usually faster" typically arise away from the computer (and easier  setup).

Version info, everything from FDroid: ulogger 1.0. MicroG 0.2.4 stable, backends LocalGsmNlpBackend + LocalWifiNlpBackend + OpenBmapNlpBackend current stable versions with offline database. Android 6.0.1 Slimrom.

**Comment by bfabiszewski** [comment]
Good idea. I will add this feature.
Though µlogger is designed to work as a server client, this option will be useful in offline situations, like yours.

**Comment by bfabiszewski** [comment]
Implemented in [Version 1.3](https://github.com/bfabiszewski/ulogger-android/releases/tag/1.3)

**Comment by TjrGithub** [comment]
Neat, thank you! I appreciate your work. I'll test and report back as soon as the new version is on FDroid. (I can't figure out where to find the .apk, else I'd test right away.)
