### ISSUE TITLE
Change of Username doesn't update correctly in App

### ISSUE THREAD

**Issue by mattfleaydaly** [bfabiszewski/ulogger-android#21]
As the title says.
I have added multiple user accounts to a server for various reasons.
A bug that i've found is that when I change the username of an account, I must either restart the device or force close the app and reopen it for the username change to take effect.
There needs to be some sort of an Apply Changes Button maybe?

If this is not a bug, please do advise :)

**Comment by bfabiszewski** [comment]
Thanks for the bug report! 
I commited a fix that removes session authorization when user changes server setup.

**Comment by mattfleaydaly** [comment]
Cheers bud!
