### ISSUE TITLE
[Feature Request] Shell control start/stop

### ISSUE THREAD

**Issue by ghost** [bfabiszewski/ulogger-android#22]
Hi, 
it would be nice to control the start and stop of tracking with a shell command. I'm planning to use this with tasker.

Thank you!

**Comment by bfabiszewski** [comment]
As far as I understand Android services it could work if I set LoggerService as [exported](https://developer.android.com/guide/topics/manifest/service-element.html#exported).

I don't know tasker, but I think than you should be able to start or stop it by [sending intent](http://tasker.dinglisch.net/userguide/en/intents.html) to the service.

**Comment by mattimatic** [comment]
I don't know if it is this what i'm looking for, but intent  I will give you an example
Now, I can already open the SettingsPage of the App with this command:
`am start -n net.fabiszewski.ulogger/.SettingsActivity`

So i think i have to know, the names of the intents for:
- start recording
- stop recording
- new track

useful link for launching with a command
https://falsinsoft.blogspot.de/2015/05/launch-app-from-android-shell-terminal.html.SettingsActivity

**Comment by frasty** [comment]
Hi,
To save battery during my rides I usually put the phone in airplane mode and I use a script (via tasker) that every half an hour automatically switches the phone back online for just a few minutes. So it would also be nice to have an intent to "manually" upload the buffered track positions (I mean without live synchronization just to make sure to save some more battery life). Thank you!

**Comment by mattimatic** [comment]
@bfabiszewski are you going to implent the possibility of starting and stopping. I hope it will work with "intend".

**Comment by bfabiszewski** [comment]
Yes. This should be pretty simple, but I need to find some time to test it.

**Comment by mattimatic** [comment]
Can you please make an alpha- / test release apk. I can help testing the APP.

**Comment by chatainsim** [comment]
This would be great to use Tasker to manage ulogger!
