### ISSUE TITLE
Refactoring Log

### ISSUE THREAD

**Issue by enieber** [bfabiszewski/ulogger-android#23]
This project is very nice, but have much duplicate code because no have one lib like [Timber](https://github.com/JakeWharton/timber) to manager logs

example:
[this code](https://github.com/bfabiszewski/ulogger-android/blob/master/app/src/main/java/net/fabiszewski/ulogger/MainActivity.java#L116)

```java
 if (Logger.DEBUG) { Log.d(TAG, "[onResume]"); }
```

will be:

```java
Timber.d(TAG, "[onResume]");
```

**Comment by bfabiszewski** [comment]
Thanks for feedback! 
I want to avoid adding third party code to this project. 
Timber is useful, but for such a small project as μlogger I can live without it.
