### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by Azimoth** [bfabiszewski/ulogger-android#24]
Hi,
I hope this is the right place for this.

I have used OwnTracks in the past, but it requires Google Play Services, which I'm happy to have gotten rid of on my phone. Hence, I'm looking for a replacement. 
Is there a way to make µlogger communicate with my MQTT broker? 
(preferably without the server counterpart, but if inavoidable I'd jump through the hoops necessary to go via the µlogger server to MQTT)

**Comment by bfabiszewski** [comment]
This is interesting, as an alternative method of uploading data. But regarding my time shortages, this would be a low priority feature, not to be implemented any soon.
