### ISSUE TITLE
How this APP works

### ISSUE THREAD

**Issue by Egauss** [bfabiszewski/ulogger-android#25]
Just wondering, its some bug or my phone. Xperia Z5 no signal or bad signal from GPS sensor, 
Open->setup settings->new track->start->and nothing
after all night got some signal on the way to work lost again, newer got back.
Any advice?

**Comment by bfabiszewski** [comment]
Difficult to say. 
You may try to tweak the settings, like minimum time, distance between updates, minimum accuracy needed for logging a position, choice of location providers.

**Comment by Egauss** [comment]
Minimum time 10s, distance 100m, GPS,  but accuracy is low

**Comment by Egauss** [comment]
It's look like Gps dosnt have fix, but with another app all ok

**Comment by bfabiszewski** [comment]
Look at minimum accuracy setting. If the value is too low (lower than GPS data accuracy) the position will not be logged
