### ISSUE TITLE
Enable import gpx to web interface

### ISSUE THREAD

**Issue by amadeous** [bfabiszewski/ulogger-android#26]
Useful when ulogger website is stored on lan and is currently unavailable. It is already possible to export the gpx file but not to import it later on. It might be useful.

**Comment by bfabiszewski** [comment]
You mean importing to µlogger server? It is already implemented.

**Comment by amadeous** [comment]
From a gpx file to the µlogger server using the µlogger ? I haven't found the way yet.

**Comment by bfabiszewski** [comment]
If you mean uploading GPX file directly from Android client, this is not supported.
I meant uploading manually through web interface.

**Comment by amadeous** [comment]
I do not have constant access to my server hosting µlogger. If I want to register more tracks. I have to export to a gpx file and I have to connect to the web interface instead of just pushing them from the app.
It could be nice to export them to a temporary location on the phone, have a counter of tracks not upload in the app and to be able to directly transfer them from the app to the server (the temporary stored gpx files could then be deleted if successful).

**Comment by bfabiszewski** [comment]
Client could be modified to support storing of multiple tracks in database. Some day :)
