### ISSUE TITLE
@ in username

### ISSUE THREAD

**Issue by smalchow** [bfabiszewski/ulogger-android#27]
Hi,

i think there is a bug, an @ in the username does not work, when i try to enter that, the application requests a "proper servername" , if i do anything else without @ i have no problem saving it

cheers
soeren

**Comment by bfabiszewski** [comment]
Thanks for the report!
You are right. I'll have to fix it.

**Comment by TomasOlah** [comment]
Any update please? I can use ulogger android client with phonetrack app in nextcloud and my login is email address. Many thanks. Good work.
Tomas
