### ISSUE TITLE
System settings for location and uLogger config seems to be duplicate

### ISSUE THREAD

**Issue by Phyks** [bfabiszewski/ulogger-android#28]
Hi,

Thanks for this very useful app! I am using it to log to phonetrack-oc app on my Nextcloud! :) My goal is to have a basic app running in the background and logging 24/7 (with quite large interval, maybe an hour).

I discovered that in the app, there is a setting to choose location source (GPS, network or both). But this setting is also present in Android itself (I can choose between high precision, or battery saving which is basically the same setting).

I was expecting I could set the uLogger setting to "GPS and network" and it would default to whatever is available. This way, I could keep it running in background and switch location mode / disable location and uLogger would cope with it, trying to find the best source for each point and not logging if location is disabled (within a same track). But actually, it seems this is not the case and I have to match the system setting with the uLogger setting :/

Thanks!

**Comment by bfabiszewski** [comment]
This setting is for filtering data source. 
For example your device gets location from network and GPS but you only want to log your position from satellite source, as most reliable.
You don't have to match it to device settings.

Generally it should work as you describe it:

> This way, I could keep it running in background and switch location mode / disable location and uLogger would cope with it, trying to find the best source for each point and not logging if location is disabled (within a same track).

**Comment by Phyks** [comment]
Not sure what happened but indeed when reinstalling and trying this again, it works as expected. Closing, sorry for the noise. I will reopen and comment if I further manage to reproduce.
