### ISSUE TITLE
Android 8 Oreo background problem

### ISSUE THREAD

**Issue by r100gs** [bfabiszewski/ulogger-android#31]
Hello,

I´m running µlogger on my Oneplus3 with Android 8. Since this update logging is not reliable working with µlogger. 
If it is in front and the screen is on everything works fine, but if it goes in background logging stops.

Turning navigation on in  google maps solves the problem at the moment. Logging works again.

Best regards, Stefan

**Comment by bfabiszewski** [comment]
Thanks for the report!
Unfortunately there are limitations for background jobs in newer APIs. 
I will have to find a solution, only need some free time :)

**Comment by r100gs** [comment]
Yes, time is always a problem. If you need sb testing the app you can write me.

**Comment by ArchGalileu** [comment]
for me also, no background.... 

is it possible to solve? 

Best regards 
ArchGalileu

**Comment by ArchGalileu** [comment]
Can we try something as:
https://medium.com/mindorks/enable-background-services-in-chinese-roms-32e73dfba1a6

Best regards
ArchGalileu

**Comment by bfabiszewski** [comment]
@ArchGalileu  
In Chinese ROMs, sometimes you have to give extra permissions to the application. I recently had an issue with Android 6 with MIUI, which needed explicit permission for extra battery usage in background: "Settings -> Additional Settings -> Battery -> Manage apps battery usage".

**Comment by anaqreon** [comment]
I just discovered uLogger yesterday on F-droid and am very impressed with it. Within twenty minutes I had downloaded the Android app and server source code repos, compiled the Android app, setup the uLogger server, and was tracking my phone's location in the web app! The documentation was clear and everything just worked. Thanks for your hard work @bfabiszewski . 

Unfortunately I discovered that background location updates are also broken for me. I am running uLogger Android app version 1.8 on LineageOS 15 (Android 8.1.0) on a Nexus 5X. I made sure that background activity was enabled and that "Battery Optimization" is disabled for the uLogger app. Hopefully someone can determine how to implement the background service compatible with more recent Android versions.

**Comment by bfabiszewski** [comment]
@anaqreon 
Could you try the beta version I uploaded earlier in this thread? 
It should solve the background service issue.

**Comment by anaqreon** [comment]
I might be able to try that, yes. Can you share the source code for it too? I'm new to Android development and I'd like to see what you changed.

**Comment by anaqreon** [comment]
I downloaded the app you linked above and it appears to be updating in the background as advertised. Nice! Is this from a branch accessible within this git repo?

**Comment by bfabiszewski** [comment]
I understand it seems to be working for you. Great!
I will have to do some more cleanup before merging and making new release. While targeting higher API I had to quit support for older versions. I'll have to remove depreciated and unused code.

In the meantime, if you find any problems with this beta version, please let me know.
Thanks for testing!

**Comment by anaqreon** [comment]
This is how open source software is supposed to work. You worked hard to make something useful and generously shared it with the world. Some random guy probably on the other side of the planet discovers your code, provides some useful feedback, and the code improves and there is even more transparency as a result. Keep up the good work!

**Comment by anaqreon** [comment]
Today I've been using the app compiled from the foreground-services branch you pushed, and I discovered that it was not working reliably until I disabled "Battery Optimization" in the Android app settings for the uLoggger app. That is, when I uninstalled the original version and installed the new one, Android applied the battery optimization to it by default, which meant that it was getting killed when in the background after some amount of time. Now it appears to reliably update positions no matter how long it is in the background. I'll provide more feedback if further testing shows different behavior.

**Comment by anaqreon** [comment]
I researched this battery optimization issue a bit more. By [requesting another permission](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS), you can allow the app to request that the user disable battery optimization without leaving the app. [There is some example code from the Syncthing app](https://github.com/syncthing/syncthing-android/blob/8a0b010773afe07aec20d2cd51050682f59824ce/app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java#L126-L158) that could provide an example for uLogger.

**Comment by bfabiszewski** [comment]
Nice find! I'll have to add it to uLogger.

Now, I am going to close this issue, as the bug seems to be resolved in 2.0 release. 
In case you find new problems regarding background jobs, you may reopen it.

**Comment by goddib** [comment]
For lack of a better place I want to thank you right here @bfabiszewski for continuing work on ulogger. This bug fix was very important to keep the tool usable. I know you're limited in time and ulogger is not your focus so I just wanted to tell you that I appreaciate fixing this. Thanks!
