### ISSUE TITLE
App crashes on launching

### ISSUE THREAD

**Issue by neupanedipen** [bfabiszewski/ulogger-android#34]
#### Expected behaviour
The app is supposed to be stable and I should be able to use it properly.
#### Actual behaviour
But the app crashes on launching disabling users to use the any features.
#### How to reproduce
1. Install the app from fdroid.
2. Launch the app.
3. The app crashes.
* App version: 2.0
* Device: Samsung Galaxy Tab 3
* Operating system: Android 4.4.2
(Ps: The app doesn't crash on Android 6.0.1 but crashes in kitkat os.)
#### Recording of the bug
https://youtu.be/LqEh8a0kxNI

**Comment by bfabiszewski** [comment]
Thanks for the report!
I didn't test enough before making this release. 
I'll push a fix in a moment.

**Comment by neupanedipen** [comment]
Thank you! That would be great.
