### ISSUE TITLE
cannot re-synchronize a track once it's been synchronized once

### ISSUE THREAD

**Issue by axb21** [bfabiszewski/ulogger-android#35]
I would like to synchronize a saved track a second time, e.g. after removing and reinstalling ulogger-server. I could not find a way within the Android app to tell ulogger to synchronize a track a second time. It tells me the track has already been synchronized, which is not quite true since I blew away and reinstalled the server.

**Comment by bfabiszewski** [comment]
Currently it is not possible to reset track synchronization status. I understand it may be needed sometimes but not very often.
The only thing you can do now is to export the track to GPX file and import it to uLogger server.
