### ISSUE TITLE
Dynamic GPS requests 

### ISSUE THREAD

**Issue by Tux12Fun** [bfabiszewski/ulogger-android#37]
Hi,

It would be nice if the App would request GPS position dynamic with higer frequency if I move or request it if the WLAN/GSM Net is changed. If I don't move the requests could be less often.

So I would have a more exact Tracking and Battery save if I sleep oder when I'm at Work. Currently the App polls every 1m for a new Position

**Comment by bfabiszewski** [comment]
You may change the time frequency in configuration. There are two factors: time and distance. The location is updated when one of these factors is triggered. Try to set distance to small value and time to larger value, like 30 minutes. Then when you move it will update positions more often. When you don't move it will update every 30 minutes.

Anyway I didn't design this app to record 24-hour life events like sleeping but rather dynamic activities involving movement like trekking, running etc. :)

**Comment by supermamie** [comment]
My 2 cents : µLogger is running non-stop on my phone for around 1 year (not linked to µLogger server)

**Comment by Tux12Fun** [comment]
Hi,

I had a look into your socurce code. Very nice wirtten. But I don't understand the LocationProvider. I've seen the Method has the minTime and Distance. Is Android query the GPS all the time or is the minTime how often the GPS Position is requested?

 locManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, minTimeMillis, minDistance, locListener, looper);

I tried to build the Feateue on my own and woud contribute to the Project.

My current try works as the following.
-> new Var. updateTime
-> updateTime = minTimeMills at start
-> if position is found and updated a Handler starts and updates the updateTime so the Request will be much slower.
-> if movement and update occurs the update time will be reset to minTimeMills.

This is only a try and my way to understand the complete code to earn the konw how to contribute a optimal code to the project.

**Comment by Tux12Fun** [comment]
I would like to use it to track all my ways and get a moving Profile of my Phone :)

**Comment by Tux12Fun** [comment]
I've done a bit of debugging on my Galaxy S2 with Android 4.1.2. The LocationListener is called every minTimeMills regardless of movement. The parameter minDistance is ignored at my phone.

Tested at my way home with: 
MinTime 5M
MinDist: 25M
Accuracity: 25M

Result  --> A waypoint every 5Min. (And my car goes more then 25m in 5 Minutes :-)

May be I found a suitable way. It the fine tuning is complete I provide the code. Maybe it could be integrated in the Main Release

**Comment by supermamie** [comment]
The app can not know if there was a movement without asking for it's position (or stay awake to track phone position, I'm sure you don't want that)

**Comment by bfabiszewski** [comment]
I agree with supermamie. Your changes are probably not suitable for normal users. First of all I want the app to be notified about every movement. Then, dynamically changing minimum time doesn't make sense. This parameter is important only when there is no movement.

Regarding your tests, there is something wrong. Either it is caused by your changes to the code, or the accuracy is set to too low value which makes app skipping location updates.

**Comment by bfabiszewski** [comment]
Regarding location update parameters, minimum distance and minimum time, read [here](https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(long,%20float,%20android.location.Criteria,%20android.app.PendingIntent))

**Comment by bfabiszewski** [comment]
> If I start moving it could take up to MaxTime to dectect this but then Track with MinTime again.

But this is the problem. MaxTime period of the track will not be registered.
This may be useful in your case, but for my purposes it is not good.
If someone rides a bike they register points e.g. every 20 seconds if they move. If they are not moving the minimum distance threshold (e.g. 100 meters) is not met, so new points are not registered.
Then if they start again the track is started to be registered immediately. 
In your case the first minutes of the track after the break will be lost.

**Comment by Tux12Fun** [comment]
That is correct and form this reason this feature is definitely a optional switch and inactive code if disabled. My current code (in test) is only a view lines and doesn't have a behavior on the normal operation if it's switched off. 

And you don't need to push it into the app. I can provide it to you if I'm ready and you can decide if you like to add it as a feature.

**Comment by bfabiszewski** [comment]
Great! 
The idea was not clear to me at the beginning. Now I see I've already forgot how minimum time and distance criteria work. Your feature may be useful for cases when high precision of track is not required. It should save some battery life.
Looking forward to your PR.

**Comment by TMaddox** [comment]
why not leverage the accelerometer and the gyroscope?

I think based on that information the phone could determine if you are sitting, walking, driving, ...?

Or is the battery consumption of these sensors too big?
