### ISSUE TITLE
Hide the notification icon

### ISSUE THREAD

**Issue by alex9099** [bfabiszewski/ulogger-android#38]
Hi,

Is it possible to hide the notification icon? i would like to use this app as a Find my device alternative, but the notification would be asking for the thief to disable the network connectivity (well, a smart thief would do that as soon as they grab the phone... but yea :D)

**Comment by bfabiszewski** [comment]
Background services without notification icon are killed by system in recent Android versions.

**Comment by alex9099** [comment]
It seems like there is a workarround which is to hide/disallow the notifications :) that way it does not show, thanks anyway :+1:

**Comment by fazlerabbi37** [comment]
@alex9099 can you please shear the workarround here? I would like to hide the notification icon from my android as well. Thanks in advance!
