### ISSUE TITLE
Error when trying to upload to demo server

### ISSUE THREAD

**Issue by gkaklas** [bfabiszewski/ulogger-android#40]
When I tap the upload button I get `HTTP error code: 400` under the synchronization section. When I tap it again I get this:
`Value <html><body><script of type java.lang.String cannot be converted to JSONObject`

**Comment by bfabiszewski** [comment]
For some reason android client can't access server script. 
Make sure you have entered proper server address in client configuration, eg. `https://www.your-domain.org`. 
Also check that web server is properly configured to serve requests from client. You may try to open client upload page (`www.your-domain.org/client/index.php`) from a browser. Properly configured server should display: `{"error":false}`.

**Comment by gkaklas** [comment]
I used the demo server provided for [ulogger-server](https://github.com/bfabiszewski/ulogger-server).

I logged in with username `demo` and password `demo`. After visiting http://ulogger.fabiszewski.net/client/index.php with a browser, I get:
`{"error":true,"message":"Unknown command"}`

So you're saying that maybe the demo server isn't configured properly? Shall I open an issue there?

**Comment by bfabiszewski** [comment]
I changed hosting (bfabiszewski/ulogger-server@c7e32e44b3f0253bf1358b198f40759badaba6a4). It should work now.
