### ISSUE TITLE
Auto Pause

### ISSUE THREAD

**Issue by dbrgn** [bfabiszewski/ulogger-android#44]
I'm thinking about using uLogger for tracking my bike  rides. One vital feature I'd need for that would be auto-pause when  stopping.

Are there any plans implementing that?

**Comment by bfabiszewski** [comment]
You can get such behaviour by setting minimum distance parameter to non-zero value. When you stop, the distance will be zero, so positions during stop will not be logged. 
When you move again and cover distance greater than minimum, it will be logged again.

**Comment by dbrgn** [comment]
Ah, thanks! I guess that will do for me :)
