### ISSUE TITLE
App uninstallable, version 1.0 present (but not visible)

### ISSUE THREAD

**Issue by marcogaio** [bfabiszewski/ulogger-android#47]
I've tried to install you app in my wife phone, but F-droid report that version 1.0 is installed, claim there's an incompatible key and, even if i enable ''incompatible versions'' there's no way to uninstall it (and so upgrade it).

If i list installed Apps, there's no such app, even enabling ''system'' app view.

Clearly phone is NOT rooted. Some hint? Thanks.

**Comment by bfabiszewski** [comment]
Strange.
If the app is not installed on the phone, I would assume that is an f-droid issue. 
Please try to get some help at f-droid issue tracker, as I don't have much experience with it. 
If the problem persists feel free to reopen this issue.
