### ISSUE TITLE
app doesn autostart on boot

### ISSUE THREAD

**Issue by francois90** [bfabiszewski/ulogger-android#49]
ULogger should start tracking location on boot when this otion is selected in the settings, but it doesn't. I have to do it manually everytime my device reboots.

Device: Xiaomi MiA1
OS: Lineageos 15.1 (android 8.1.0)
App version: 2.2

Note: start at boot is allowed in privacy guard

**Comment by bfabiszewski** [comment]
Thanks for the report!
I committed some [changes](https://github.com/bfabiszewski/ulogger-android/commit/72d32f4447b8dbfe4873dbec5eddaf580d2754dc) since the last release that address similar issues. I hope it will solve your problem.
I hope to release new version soon.

**Comment by francois90** [comment]
Thank you!

**Comment by francois90** [comment]
The issue is fixed since last update on fdroid. Thank you
