### ISSUE TITLE
Crash on Android 9

### ISSUE THREAD

**Issue by jarek556** [bfabiszewski/ulogger-android#50]
I've tried to run uLogger on two mobiles with Android 9 (Moto X4, Nokia 7 plus), and application crashes, after click on "Start". 
The same configuration works fine on Android 8 (Moto G6 play).
On Android 9, uLogger don't asks for permitions, but setting them manually doesn't help.

**Comment by bfabiszewski** [comment]
Thanks for the report. I'll check it.
