### ISSUE TITLE
FR restart track after update

### ISSUE THREAD

**Issue by Buntbart** [bfabiszewski/ulogger-android#52]
Thank you very much for ulogger on F-Droid!

I wonder if ulogger could automatically start again logging the current track after an update. At the moment this track has to be started manually after every update. Autostart is activated already, but doesn't work if the phone is not rebooted.

Thank you in advance!

**Comment by TjrGithub** [comment]
This bug bit me, too, because I use ulogger for 24/7 tracking and have FDroid on autoupdate.
