### ISSUE TITLE
cannot export huge gpx file

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#54]
Ulogger cannot export a track as a gpx file once it reaches around a million data points. It simply hangs and gives no error message.

I use ulogger as an always-on, completely-offline GPS/NLP tracker for privacy reasons. There is no way to start a new track (since that would delete all previous data), so I'm stuck pushing everything into one single track. Over time, it has grown to over a million data points.

The workaround is to open an Oandbackup backup of the app database on the desktop with an sqlite editor.

Maybe some database code could be lifted from Tiny Travel Tracker? It is designed to handle that many data points.

**Comment by bfabiszewski** [comment]
Thanks for the report. I'll fix it.

BTW I am afraid the app is not suitable for your needs. Sooner or later you will face more problems.
The only thing I don't understand is why don't you start a new track each time after exporting data to GPX. You could have a backup history in GPX files and only latest period on your mobile device. You could even start a local instance of µlogger server on your PC and upload data by local network or by GPX import.

**Comment by TjrGithub** [comment]
Thank you.
Yes, my usage isn't quite intended - so far, ulogger does the job, and it's the only reliable fire-and-forget tracking app on FDroid.

I'll try running a ulogger server locally if I need to access the data more frequently.
