### ISSUE TITLE
self-signed certificate error

### ISSUE THREAD

**Issue by circledot** [bfabiszewski/ulogger-android#55]
I get the following error, and I'm fairly sure it's because I'm using a self-signed certificate. I would like the app to ask me if I want to accept it or not.

Thanks

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by bfabiszewski** [comment]
Application should work with self signed certificates. 
You must add your CA certificate to Android trusted root certificates.

**Comment by circledot** [comment]
Perhaps, but I know people that might use this app and they need something user-friendly.

**Comment by bfabiszewski** [comment]
Now that we have free good quality certificates (eg. Let's Encrypt), self-signed ones are not so popular any more. I don't plan to add extra support for it. 
Also the recommended, secure way of handling such certificates is through operating system trusted certificates store, both on mobile and desktop platforms.

**Comment by NK308** [comment]
I'm getting the same Error with a self signed certificate, but my certificate IS added to the trusted certificates in android.

**Comment by bfabiszewski** [comment]
Which Android version?
Important thing is you must add your certification authority (CA) certificate to trusted store, not server certificate.

**Comment by NK308** [comment]
Android 9 (LineageOS 16)
I added the certificate in the security options to the Trusted credentials.
Also my nextcloud client on the phone never complained about certificate issues.

**Comment by bfabiszewski** [comment]
I was testing self-signed certificates handling with previous Android versions and it worked fine. I didn't test it with latest versions, but I don't find any changes in recent APIs.
I also didn't test it on LineageOS. Maybe there are some additional restrictions?

Are you able to connect to µlogger server from web browser on the mobile device (over https)? Is the connection marked as secure without adding any exceptions?
Maybe you are trying to connect to a subdomain, which is not covered by your certificate?

It seems that Nextcloud client allows to [use untrusted certificates](https://github.com/nextcloud/android/blob/deffbd8b00677f93789e769c4fd2ff971a7ac158/src/main/java/com/owncloud/android/ui/activity/FileActivity.java#L435). Maybe that is your case? In µlogger client there is no possibility of accepting certificate issued by untrusted CA. So proper root certificate installation is crucial.

**Comment by haywardt** [comment]
I am getting this error on a ZeroSSL certificate. Browsers have no problem using https on windows and android, but the ulogger client is showing this error.

**Comment by bfabiszewski** [comment]
Which Android version?
Maybe intermediate certificate is not installed on server?
Some browsers may use their own certificate stores, while µlogger uses system one.

**Comment by haywardt** [comment]
it looks like the ZeroSSL certificate chain is incomplete according to [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=haywardt.42web.io) Strange that all the browsers work, but the client doesn't. Still it looks like a certificate issue.

You might add a note in the readme that TLS is required. Figuring that out took me longer than it should have.
