### ISSUE TITLE
Request: Hide persistent ulogger notification

### ISSUE THREAD

**Issue by circledot** [bfabiszewski/ulogger-android#56]
I don't mind ulogger in my notifications area but don't particularly want it there all the time.

Please post dash address so I can tip.  Thank you.

**Comment by bfabiszewski** [comment]
Notification is needed in order to keep background service alive. It is Android system requirement. Otherwise service will be killed.
It might be possible to hide it from Android App settings, haven't tried it.

**Comment by circledot** [comment]
Well, I can probably mute all notifications, but what if you later add notifications for some other function? 

I understand the google restriction thing, but some apps - such as the "Volcanoes & Earthquakes" app seem to of got around it somehow.

**Comment by bfabiszewski** [comment]
I don't know volcanoes app. Its description suggests it may receive push notifications from Google FireBase service. 
The way µlogger works is optimised for low resources usage, long battery life and privacy. It does not contact any third party services. It doesn't use Google fused location provider. It depends on foreground service to get real time location and needs notification icon to stay alive.

**Comment by Evidlo** [comment]
I can confirm that `Settings > Notifications > App notifications > µLogger > Block all` has the desired effect.
