### ISSUE TITLE
[Feature request] Track name prefix in Settings

### ISSUE THREAD

**Issue by circledot** [bfabiszewski/ulogger-android#58]
At the moment, a new track is prefixed with "Auto_", I want to set my own default within the client to assist identifying multiple devices. 

Also, can you add a Dash address for donations?

Thanks

**Comment by bfabiszewski** [comment]
Sounds good, I'll give it a try.

**Comment by bfabiszewski** [comment]
I just noticed Fdroid finally included the version implementing this feature in their repo. You can test it now.

Dash address added. My donations section looks impressive now!
