### ISSUE TITLE
Get error on sync

### ISSUE THREAD

**Issue by 451732** [bfabiszewski/ulogger-android#59]
get this error while live sync or upload:

Value 66 of type java.lang.integer cannot be converted to JSONObject

App is running on Motorola G6+ with Android 9

thx for help

regards Mike

**Comment by bfabiszewski** [comment]
Difficult to tell without deeper look at the conversation between server and client.
It looks like the server is returning malformed response.
What do you see if you enter client address in a browser? Add `client/` to your base URL, eg. `www.yourhost.org/client/`.
There may also be a problem with your hosting. I know that some free hosting servers are attaching some javascript to each response to prevent non-browser access. See this [issue in µlogger server](https://github.com/bfabiszewski/ulogger-server/issues/17) for more info.

**Comment by 451732** [comment]
Solved!
Thx for help! It was a misconfiguration of my server
