### ISSUE TITLE
Thanks for the app, issue: don't get location

### ISSUE THREAD

**Issue by nmezheri** [bfabiszewski/ulogger-android#6]
First let me thank you for the app, and making it open source. I was on the way to create one for myself, I was a long user of TrackeMe (under windows mobile 6, then Android). For some reason, the app can't get any location, I have network cells and gps in the settings, and I have gps enabled. I'm on LOS 13.0 and I noticed that the app did not ask for location permissions, wondering what I'm missing. I don't allow google services to manage my location maybe the issue if you rely on them. Any way to have the application to get gps coordinates itself. Thank you.

**Comment by bfabiszewski** [comment]
Thanks for trying it out!
I think you may be affected by a bug (app not asking for location permission, #4)  that was fixed in version 1.3.
Could you please upgrade to 1.3 and try again.

If the problem persists please reopen this issue.
