### ISSUE TITLE
[Enhancement]: Possibility to store waypoints

### ISSUE THREAD

**Issue by hubertmeier** [bfabiszewski/ulogger-android#60]
Thank you for your program, i use it to tag my photos with the rekorded track, it works fine. Sometimes i use it for Openstreetmap - Mapping and i miss the possibility to store some waypoints.

There is a now button "New track". What about a second button "New waypoint list" and a furter button to add a waypoint, perhaps with an input-field for a comment.

With the button "Upload" the track and the waypoint-file ist copied to the download-folder.

**Comment by bfabiszewski** [comment]
This feature is on my [todo](https://github.com/bfabiszewski/ulogger-android/blob/76be3d79ffb21e606606ab4cfff851b0a7428edd/app/src/main/java/net/fabiszewski/ulogger/WebHelper.java#L67) list from the very beginning. 
If I only find some time I want to implement a function to manually add position with possibility of attaching a comment or an image.

**Comment by hubertmeier** [comment]
OK, thank you, it is not so important but it would be nice to have ...

**Comment by bfabiszewski** [comment]
FYI This is implemented in 3.0 version
