### ISSUE TITLE
[enhancement] display GPS-status

### ISSUE THREAD

**Issue by hubertmeier** [bfabiszewski/ulogger-android#61]
it would be nice to see the actual stats of the gps-system (number of satelites, actual position and especially the accuracy of the position) when the app is in the foreground.

**Comment by bfabiszewski** [comment]
I am not sure I need it. There are many GPS loggers with lots of features. I'd rather focus on simplicity.

**Comment by rahra** [comment]
IMO this is out of the scope of this app. There are plenty of other apps focusing specifically on GPS details. E.g. have a look at this: https://f-droid.org/en/packages/com.vonglasow.michael.satstat/
