### ISSUE TITLE
[enhancement] adding 3s and / or 5s to the intervall list

### ISSUE THREAD

**Issue by hubertmeier** [bfabiszewski/ulogger-android#62]
for OSM-Mapping the 10s interval is too long, sometimes for photos too. I know, 10s is surely good for the battery but 10s could be the default

**Comment by bfabiszewski** [comment]
You can choose `other` and enter any value manually. You probably won't change it very often.
I don't plan to extend the presets list with shorter or longer values. The value you need very much depends on your particular use case. For example I never use interval shorter than 30 seconds.

**Comment by hubertmeier** [comment]
OK, thank you, that would work for me, i didn't see that ...
