### ISSUE TITLE
[enhancement] comments on track points

### ISSUE THREAD

**Issue by rahra** [bfabiszewski/ulogger-android#64]
It would be nice to have a text field within the app allowing to post a note which is in turn added to the next track point.
On the server side this could then be displayed directly on the map.

With this you could mark in "real-time" specific places during your trip which would immediately be visible to spectators of your track.

**Comment by bfabiszewski** [comment]
I have already implemented such a feature in my local branch – it allows to add comments and images to waypoints. It just needs some more polishing and testing. 
But it also needs changes on the server side. I will release it as soon as I have both sides ready.

**Comment by hungerburg** [comment]
Oneline texts that get exported to GPX waypoints would be nice to mark features, eg. for use in OSM mapping.

**Comment by hungerburg** [comment]
Cool that the feature is in now; Meanwhile I just took pictures and while ulogger is tracking, they all have coordinates ;) Thank You nevertheless!
