### ISSUE TITLE
Using with Easer

### ISSUE THREAD

**Issue by Evidlo** [bfabiszewski/ulogger-android#68]
[Easer](https://github.com/renyuneyun/Easer/) is a FOSS alternative to Tasker.  I wanted to use it to tell µlogger to start a new track every day, but the broadcast fields don't seem to match up with the README.  Any idea what goes in the `Category` or `Type` fields?

![Screenshot_20191109-160526](https://user-images.githubusercontent.com/5455841/68535657-4aa3e500-030b-11ea-8da8-2d3ce28da446.png)

**Comment by Evidlo** [comment]
I found that the `Run commands` profile works just as well with `am broadcast -a net.fabiszewski.ulogger.intent.action.COMMAND -e "command" "start new logger" net.fabiszewski.ulogger net.fabiszewski.ulogger.ExternalCommandReceiver`.

**Comment by bfabiszewski** [comment]
Maybe Easer doesn't support custom target for broadcasts?

Nice that `Run commands` works.

**Comment by bfabiszewski** [comment]
It seems broadcasts are currently broken in Easer. 
See https://github.com/renyuneyun/Easer/issues/470#issuecomment-1761056239
