### ISSUE TITLE
Download all tracks in single .gpx

### ISSUE THREAD

**Issue by Evidlo** [bfabiszewski/ulogger-android#69]
GPX files are capable of holding multiple tracks.  Instead of the download button only getting the latest track, wouldn't it make more sense to package all recorded tracks into a single file?

**Comment by bfabiszewski** [comment]
Android app can only store one track.
If you mean web interface export I usually export only single chosen track when I need to import it to another application. Exporting all tracks (can be hundreds of them) could be an option.

**Comment by Evidlo** [comment]
> Android app can only store one track.

I guess that's a prerequisite for this feature then.  It would probably be
good to be able to store more than one track if away from cellular networks
for multiple days.
