### ISSUE TITLE
Cannot use standard port 80

### ISSUE THREAD

**Issue by biotecov** [bfabiszewski/ulogger-android#70]
Hello, I try to set the server url with a port, but this does not seem to work (timeouts). I am behind a firewall and I can use and forward almost every port, EXCEPT the most usual ports (80, 443, 22 and the like). Is it possible to set the android client to connect to a server on a non-standard port? For example to 8080, or whatever. If it is already possible, how to set it up

Regards.

**Comment by bfabiszewski** [comment]
It should work with scheme `https://www.example.com:8080`. 
Double check your firewall settings. Maybe you are blocking access?
Also make sure your website is accessible from browser on given port.

**Comment by biotecov** [comment]
it works now, thank you
