### ISSUE TITLE
Unusual coordinate format in "New Waypoint" window

### ISSUE THREAD

**Issue by rahra** [bfabiszewski/ulogger-android#71]
I just looked at the dev version of ulogger and the waypoint feature is really great!
But I found that the position in the "New Waypoint" window is displayed in a pretty uncommon way.
Did you have any special thoughts on that, or "did it just happen"?
As to my best knowledge as a seaman there are 3 common formats:
* degrees and minutes with 1 (or 2) fractional digits (e.g. 47° 28.52' N)
* degrees, minutes and seconds (used almost only in the US, e.g. 47° 28' 31'' N).
* degrees and its fractional digits (e.g. 47.475 N).

I'd file a pull request to fix this, if it doesn't have any special meaning now.

**Comment by bfabiszewski** [comment]
What I use is DMS format (number 2 on your list) with enhanced precision 47° 28' 31.1234'' N. One second of latitude or longitude on equator is around 30 meters. Some devices offer GPS precision below that, 5–10 meters IIRC. It is of course questionable if we need that precision or not. I thought it may be useful and I am accustomed to DMS format.

Maybe we could give user a choice between different formats? Selected in app preferences.

**Comment by rahra** [comment]
Ah, ok, now this makes sense. I thought you somehow mixed seconds and fractional minutes.
I'm personally used to format 1 (of my list) which is mostly used in marine application.
Nevertheless, 4 fractional digits IMO is little bit too much precision, it's 3cm ;)

A format choice would be nice, so let's see this as a feature request.
