### ISSUE TITLE
Clear database

### ISSUE THREAD

**Issue by ksz16** [bfabiszewski/ulogger-android#73]
First of all I wanna thank for you work.
ulogger is extremely useful - it can work in offline mode and allows to track incredible amount of hours (thanks to its lightweight and flexible config). This is very important especially for trekking activities.
I think that ulogger's strength is in its simplicity, so in my opinion you should not to add a lot of new features, and consider this app as a kind of completed project. But I miss one little feature: possibility to clear database from GUI.
Would you consider my request? 
And just one more thing: I think moving Export button to one line with Start, Upload, New Track would make interface more coherent.

**Comment by ksz16** [comment]
![ulogger](https://user-images.githubusercontent.com/22708888/75269284-f3ae1700-57f8-11ea-998e-bdef2ff503ad.png)

**Comment by bfabiszewski** [comment]
Thanks for the comment!

I agree some kind of database cleanup would be handy. I was planning to implement it some day.
But I don't think it should be present as a button on the main screen. At least for me this would be extremely rarely used function. Usually I just leave the old track in the database until I start new one which automatically removes it. The database size is very small so I don't care.
The same applies to "Export" button. I designed the application for online synchronization. And the main screen reflects this basic usage. Export is used only in rare cases when I can't upload track to the server. 

BTW I already redesigned the main screen for the new version (not yet released) to make space for the new button "Waypoint". With this button you can add waypoints with attached comment and image.


![device-2020-02-26-125737](https://user-images.githubusercontent.com/3366666/75343152-21966880-5898-11ea-8e9e-bc5add3a0e91.png)

**Comment by bfabiszewski** [comment]
FYI I added clear track option to menu in 3.0 version

**Comment by ksz16** [comment]
I've already noticed - I'm using a new version :-)
Thank you very much.

I don't use the server part of the application, using it only for offline tracking. Hence my ideas for changes in the main screen. But I understand your argumentation.

Thanks again for the great soft.
Greetings.
