### ISSUE TITLE
Waypoint : impossible to upload image

### ISSUE THREAD

**Issue by Thieume** [bfabiszewski/ulogger-android#74]
Hi,
Here is my set-up :
- Server updated to 1.0 release.
- App updated via F-Droid with 3.1 release
- Owner of a Samsung Galaxy S9 with a stock android version (no root)

I can use µlogger app without problems for its "normal" work. I can add waypoints only if I put text.
I have an issue when I try to attach an image (I take a photo or I attach a previous image). 

Photo 01 : the UI works correctly, I can attach and click on the "Save" button
Photo 02 : all seems to be OK, 1 position has to be uploaded.
Photo 03 : The app says that the server has encountered an error.
--> From now all the uploads are blocked. 

I have seen in my Nginx logs, on the server and I haven't found errors. 
I don't know where I have to look at to find log file on my android device.

I put this issue as "important" because I cannot continue to upload positions and my trace is completly stuck. I can only delete it (with a loss of all the pending points) and recreate a new one. 

I am available to dig more in order to give you bug informations...
![03](https://user-images.githubusercontent.com/3884674/85984527-9960d500-b9e9-11ea-961b-695693606e64.jpg)
![02](https://user-images.githubusercontent.com/3884674/85984529-99f96b80-b9e9-11ea-8a56-b8264f9928e3.jpg)
![01](https://user-images.githubusercontent.com/3884674/85984532-9a920200-b9e9-11ea-921a-e5c2bac9ca47.jpg)

**Comment by mapl** [comment]
I am have the same issue. Thanks for opening the issue.

**Comment by bfabiszewski** [comment]
Maybe PHP doesn't have write permission for uploads folder?
Can you upload a picture from web UI (edit position dialog)?

How did you do migration to 1.0, script or manually?

**Comment by bfabiszewski** [comment]
Until the problem is solved you may want to export current track (export GPX) from Android app as a backup. It can be imported through web interface (without images).

**Comment by bfabiszewski** [comment]
You may also check whether you are not exceeding maximum upload size for your server in nginx or php settings.

**Comment by Thieume** [comment]
Hi,
I can upload images with the web UI. It works correctly.
I have checked on the server and the file owner is correct for the "uploads" directory and other µlogger files.
No problem for the "upload_max_filesize" with PHP (32MB with a 2MB image). All the "upload_*" options are set to 32M.

For the 1.0, my server has never seen the previous release. I installed µlogger may be 1 month ago starting from the files available on GitHub. Based on that, the 1.0 release has replace the 1.0.beta, manually.

**Comment by bfabiszewski** [comment]
The message you receive on the app suggests it is a server issue.
In the PHP application errors are logged using [`syslog`](https://www.php.net/manual/en/function.syslog.php) command with `LOG_ERR` priority. The log file where the error message will land depends on `syslog` configuration in your distro (I assume it is unix). It might go to nginx or PHP logs, but also it may be logged to `/var/log/syslog` or `/var/log/messages` or other log. 
So please check all the system log files. Maybe there will be some clue.

**Comment by Thieume** [comment]
It's installed on a Synology NAS. I'll have a look...

29 juin 2020 20:06:52 Bartek Fabiszewski <notifications@github.com>:

**Comment by Thieume** [comment]
I dig a bit more and I do not see troubles in the logs : syslog / messages / error_log ... No recent entries.
I have made this morning a new tracking with a photo waypoint and I have seen this this morning (see attached file)
![2020-06-30 09_22_21-Window](https://user-images.githubusercontent.com/3884674/86096181-3fc4dd00-bab3-11ea-924a-b4c71533eaa4.png)

**Comment by bfabiszewski** [comment]
This might be an issue with size of the image being over limit.
What is the size of the file you are trying to upload?
Does it also happen with a small, let's say 1 px image?
You already checked PHP settings. You may also check nginx settings regarding size limit, eg. `client_max_body_size`.

**Comment by Thieume** [comment]
Hum, client_max_body_size is set to 0 (so disabled).
I can create a waypoint with a 1px image (95B) but I cannot upload a waypoint with a 100KB image.

Moreover the NAS application is very strict and I cannot modify the internal parameters of Nginx. All the conf files are rewritten by the system when NGinx is restarted... Sad !

I do not understand one thing : if I'm able to upload images with the WebUI (2MB and more) it seems that the server is capable of transfering "big" files. The app shall be normally able to do the same, no ?

In order to be sure that it is my server which is faulty, is it possible to provide me a temporary account on a well configured server ? With that I can really be sure that the Android app and my phone aren't the problem...

**Comment by bfabiszewski** [comment]
Android app uses different approach for uploading positions than your browser. Most notably µlogger app connection uses chunked encoding and I suppose that under specific server setup it fails for some reason. 
I don't have any demo server where you could upload image. It doesn't work on my Heroku demo, because of this provider restrictions.
Anyway I have an idea, how to solve it. I would need your configuration to test connections but I can't reproduce it. Maybe you could add temporary test user on your µlogger server for my tests? You could send me login credentials by a private message. My contact data is on my webpage: www.fabiszewski.net. 
I would try to upload an image with my debug client to get more insight to the problem. I could also try to modify the client and see if that helps.

**Comment by virtadpt** [comment]
I'm running into the same problem; tracking this ticket to figure out what the fix is.
