### ISSUE TITLE
not in fdroid website anymore

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#77]
What's not there anymore:
search for ulogger in the Fdroid website.
https://search.f-droid.org/?q=ulogger&lang=de
https://search.f-droid.org/?q=fabiszewski

What's still there: 
https://f-droid.org/de/packages/net.fabiszewski.ulogger/
https://f-droid.org/wiki/page/net.fabiszewski.ulogger

**Comment by bfabiszewski** [comment]
Maybe search doesn't work on Fdroid site. Please report there.

App is available here: https://f-droid.org/en/packages/net.fabiszewski.ulogger/
