### ISSUE TITLE
javax.net.ssl.sslprotocolexception Bug

### ISSUE THREAD

**Issue by Mottek57** [bfabiszewski/ulogger-android#79]
Hallo Bartek,

Great work... I love your  µlogger...

But I have an old 4.4.x-Android device, witch get this error:
"javax.net.ssl.SSLProtocolException: SSL handshake aborted" and "routines:SSL23_GET_SERVER_HELLO sslv3 alert handshake faiure"

Its looks, that µlooger try to create a secure connection, but TSL 1.2 is disabled in Android 4.4.x an it try an fallbacl in SSLv3...
I found this in the web: https://www.it-swarm.dev/de/java/android-4.4.2-ssl-handshake-abgebrochen/822810262/

Can you fix it?

Thanks...

Volker

**Comment by bfabiszewski** [comment]
Thanks for reporting. I already had [solution for similar issues](https://github.com/bfabiszewski/ulogger-android/blob/cba50d81ca0603bce1c2577164b595bb323fcfaa/app/src/main/java/net/fabiszewski/ulogger/TlsSocketFactory.java) but removed it. Probably too early. I will reapply it.
