### ISSUE TITLE
wishlist: acquire position for free whenever another app already requested it

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#8]
Hi,
would it be possible to make ulogger also read out the GPS / network position whenever another app has already requested the position (and incurred the battery drain)? This would further reduce power usage, because ulogger gets the position once for free and can wait longer until it requests the next location update from the OS.

Role models: This app acquires the GPS position and wifi scan results for free whenever another app initiates the scans:
https://f-droid.org/repository/browse/?fdfilter=backend&fdid=org.fitchfamily.android.wifi_backend

This app aquires the GPS position and displays a notification whenever another app scans for position: https://f-droid.org/repository/browse/?fdfilter=satstat&fdid=com.vonglasow.michael.satstat

Thanks for the great app!

**Comment by bfabiszewski** [comment]
This is certainly possible. There is so called passive location provider available. I was considering adding it to the list of location providers but finally I didn't. 

I will try to experiment with it and see if it offers any improvements.

**Comment by TjrGithub** [comment]
One usage scenario is: A navigation app (Osmand) requires the GPS, and at the same time I'd like to have a complete location profile all in one place, i.e. in ulogger.

**Comment by supermamie** [comment]
I think OsmAnd was just an example and it could be good not to request gps again if another app used it 2 min ago.

I really need to re-do pull request #20 to make it usable, I'm not sure I'll have time this year but this is a somewhat good start if someone want to implement it.

**Comment by TMaddox** [comment]
+1 for this, would be awesome! This would increase accuracy, without the cost of additional battery drain

**Comment by TjrGithub** [comment]
I'd still be delighted to see this, if you decide to implement it.
