### ISSUE TITLE
No upload possible

### ISSUE THREAD

**Issue by smsgthb** [bfabiszewski/ulogger-android#80]
Upload oft track to Server does not work. Tested with own server and demo page on herokuapp.com

> URL fehlerhaft: no protocol: ulogger-demo-herokuapp.com/client/index.php

ulogger version 3.02 (from F-Droid.org)
Smartphone: Huawei Mate 20 Lite, Android 10.0.0.245

URL in browsers shows:
> {"error":true,"message":"Unauthorized"}

**Comment by bfabiszewski** [comment]
You should set full URL including protocol: http or https.

Also demo site domain name is invalid in your example: ulogger-demo-herokuapp.com. There is a typo.

**Comment by smsgthb** [comment]
Thank you very much for your fast reply.  Typo was only in my post above.
Works now with full URL. thanks.
