### ISSUE TITLE
Not syncing with PhoneTrack Nextcloud

### ISSUE THREAD

**Issue by Valdnet** [bfabiszewski/ulogger-android#83]
There is an HTTP error code: 500 when syncing with PhoneTrack Nextcloud. Device location points are not sent to the server.

![obraz](https://user-images.githubusercontent.com/47037905/95433578-6dda7880-0950-11eb-8f66-dc29e890024a.png)

Ulogger app correctly configured:

![obraz](https://user-images.githubusercontent.com/47037905/95433692-95c9dc00-0950-11eb-8234-94894baa1a45.png)

App:
Ulogger 3.3
Nextcloud 20.0.0
PhoneTrack 0.6.5

**Comment by bfabiszewski** [comment]
You will have to ask at PhoneTrack or Nextcloud. I have no experience with those apps.
