### ISSUE TITLE
ulogger-client for Apple?

### ISSUE THREAD

**Issue by Mottek57** [bfabiszewski/ulogger-android#85]
Hi Bartek,

Great work... I love your µlogger...
...and have send you a little bit over paypal... :-)

A question: Is it posible to create a ulogger-client for Apple devices?
Or is there a other client, whock works with the ulogger-server?

Some friends of me are excited what i do with the ulogger, but they use an ipad... :-\
No luck...

Thanks...

Volker

**Comment by bfabiszewski** [comment]
Thanks a lot for the support!
The problem with iOS client is that I don't own any such device and also it would require much more time to write and maintain. Maybe some day?
