### ISSUE TITLE
Auto new track every day

### ISSUE THREAD

**Issue by chross** [bfabiszewski/ulogger-android#86]
Hi!
I really love this app. As I am using it to track my whereabouts, it'd be great if there was an option to automatically start a new track every night at a preset time.

Cheers,
chross

**Comment by bfabiszewski** [comment]
The main focus of this app is on tracking outdoor events. So I'd rather not add this feature.
But I know that users who track their lifetime like you use external task schedulers to achieve it.
See [automating](https://github.com/bfabiszewski/ulogger-android#automating) section

**Comment by chross** [comment]
Thanks. Tasker did the job.
