### ISSUE TITLE
Minimum distance doesn't seem to be working.

### ISSUE THREAD

**Issue by Kj-is-escape** [bfabiszewski/ulogger-android#88]
Either minimum distance is not working or i'm not understanding how it works. 
I've set the minimum distance to 100m and just stayed in the same place and it has logged multiple updates about 10m apart. 
As I understand it markers should only be logged if they're more than 100m apart from the previous one.
![image](https://user-images.githubusercontent.com/68979736/99305674-d90e4900-2832-11eb-9bd4-973c0000fa1e.png)
![image](https://user-images.githubusercontent.com/68979736/99305574-b845f380-2832-11eb-8675-29c4f8d37f71.png)

**Comment by bfabiszewski** [comment]
Hi! Thanks for the report. 
I can think about a scenario when it happens. It never really bothered me as it only happens when you don't move and you get poor accuracy readings. I'll have a look at it and try to fix it.
