### ISSUE TITLE
Ability to export last N points

### ISSUE THREAD

**Issue by gitbaby** [bfabiszewski/ulogger-android#89]
Hi Bartek,

Thanks for this excellent tool! I'd like to request an improvement. Since µlogger is designed to quietly work in background, it may run for months and create a huge log. It would be great to be able to export to GPX only last recorded points. For instance, last 1000 points or last 24 hours of recording. Please consider this feature in the next release.

**Comment by bfabiszewski** [comment]
I don't think I will go in this direction. I really want to keep this program small and focus on tracking short time activities.
You could use scheduler to stop tracking once a day, upload it to server and restart.
