### ISSUE TITLE
[Feature request] Autocreate daily tracks.

### ISSUE THREAD

**Issue by imraro** [bfabiszewski/ulogger-android#9]
It will be nice to have this feature.

P.S.: Thank you for developing this software!

**Comment by chatainsim** [comment]
+1 ! Would be nice.
Thanks for this great app.

**Comment by MalakymR** [comment]
This is what stands out to me when using it as well - looking at someone's track is kind of useless when its full of days - and I can't get others to constantly update their track.

Alternatively - being able to filter someone's track to "last day", or "last hour" on the web ui would cut a lot of fluff from the view.

**Comment by bfabiszewski** [comment]
I designed the app to record outdoor events, like hike or bike routes. It is not well suited for 24/7 tracking. 
I think the best solution will be the possibility to filter tracks by time, as @MalakymR suggests on [server issues](https://github.com/bfabiszewski/ulogger-server/issues/35).

**Comment by fm444fm** [comment]
I also think the app would benefit a lot by an option to autocreate new daily tracks (e.g. at midnight). To be on the safe side, you could restrict autocreate of new tracks only if previous data is synchronized with server.
Maybe you designed the app primarily to record outdoor activities, but I think a lot of people are using it as day logger, gps breadcrumbs, children tracking.. and so on. If an app has multiple diverse usercases I think it's a very good thing.

**Comment by MalakymR** [comment]
I think also it could be used for 24/7 tracking too without much to do - though don't think the tracks management should be done on the device itself. For 24/7 it should be independent of a track, being an optional setting by the user with time filters otherwise.

**Comment by supermamie** [comment]
I currently use µlogger for a 24/7 tracking, using NextCloud / phonetrack as a server ( https://gitlab.com/eneiluj/phonetrack-oc ) and I really think the day-to-day separation should be done on server side, not inside the app.
An option client-side could be good for a gpx export, not really for a server export

**Comment by bfabiszewski** [comment]
If I only find some free time I will try to implement it on the server side

**Comment by fm444fm** [comment]
Why not adding a simple option inside the app, that when selected it will start a new track each day at midnight? It is much easier and would work with the existing server UI without making any changes or requiring filtering actions and such.
Also, even if filtering were to be implemented server side, it would still becomes unpractical (and I guess slow in the long term) to have a huge track comprising several months of data.

**Comment by anmol26s** [comment]
+1

**Comment by peteman52** [comment]
Great app, I use it daily.
+1

**Comment by shtrom** [comment]
I'm looking at https://github.com/bfabiszewski/ulogger-android/blob/6d87c1d02d24096a3b2a3c494ea8306b221ba0f2/app/src/main/java/net/fabiszewski/ulogger/LoggerService.java#L379 and thinking that it should be relatively easy to add something around there.

The question, though, is what is “daily”? Every 24 hours? Or everytime we clock around midnight? In which timezone?

**Comment by MalakymR** [comment]
Either way you would want to configure it, because if someone was doing something nightly etc it would "ruin" it.

Though this does show that this isn't a great idea - and should be handled on the server side.

The "track" should be made NOT required, and only used as a tagging exercise to the entry in the database. This then allows a lot of after-the-fact manipulation on the web side. Last hour, last 12 hours, between X and X etc.

**Comment by shtrom** [comment]
On Mon 03 Sep 2018 at 02:06:05 -0700, MalakymR wrote:
> The "track" should be made NOT required, and only used as a tagging
> exercise to the entry in the database. This then allows a lot of
> after-the-fact manipulation on the web side. Last hour, last 12 hours,
> between X and X etc.

I think you're right. The track change from the app would just be an
event that indicate a good time-point at which to cut the track, and give a
name to that segment.

This kills my steam in trying to get a solution for it, though. \:

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by MalakymR** [comment]
No need to "cut" the track. Would be easier just to log to the database without a "tag" for the entries. Everything then is done by date, or optionally a name for the track tagged onto every database entry whilst its running.

**Comment by shtrom** [comment]
One may want to have/add multiple tags on an an entry/track, though.

Granted any tag can be added once to all the matching points (that's what I meant by cutting; not necessarily separating the data as much as making it distinguishable).
