### ISSUE TITLE
Automate GPX export

### ISSUE THREAD

**Issue by gitbaby** [bfabiszewski/ulogger-android#90]
Currently if you want to see your track in the maps app, you need to export it manually first. It's a bit annoying to do it every day. This step could be automated. Similar to the "start upload" there could be a "start export" command. It would require a section in the settings to enter export file path, file format and how many points to export, e.g. last 1000 points or last 24 hours of recording.

**Comment by bfabiszewski** [comment]
This is related to #89.
You can also upload track to µlogger server. You will avoid moving files manually. 
Then you may combine it with scheduler to restart track periodically.
