### ISSUE TITLE
Sync with nextcloud/phonetrack fails

### ISSUE THREAD

**Issue by hast0011** [bfabiszewski/ulogger-android#91]
Hello,
I cant sync to my nextcloud server with todays install from fdroid. I am using nextcloud 20.0.2 and phonetrack 0.65 as server.

Within uLogger it says the point was uploaded but the server wont show it. When I change the server-link within uLogger it also says upload OK but that seems strange:-).

The server link looks like https://xxxxx.xxx/index.php/apps/phonetrack/log/ulogger/zzzzzzzzzzzzzzzzzzzzzzzzzz/yourname and I can replace zzzzzzzzzzzzzzzzzzzzzzz by anything else.

How can I get more information about this problem. How to solve it?

Maybe the problem is also in nextcloud/phonetrack as I did an update there also. The link shown in their documentation as "example" is also confusing a little bit as it does not contain index.php as it is shown in their web interface.

Thank you.
Steffen

**Comment by bfabiszewski** [comment]
Hi,
You will have to ask at nextcloud. I don't have any idea about it. Never used it.
