### ISSUE TITLE
does not collect network position unless gps is available

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#93]
I let ulogger run long stretches of time. It is set to collect data from GPS and network providers. I would expect it to collect network position data even if gps is not available, as it did in the past - but not in the current version.

The network position provider is always available (via microg, local gsm backend), but GPS sometimes is or is not (turning it on and off system-wide automatically via system profiles, or simply bad reception inside a train or building). In past versions (up to 3.3), it would simply collect the data that is available. That means, if GPS is turned off system-wide, it would write out network positions - just as I would expect.
However, in version 3.4 FDroid, it stops collecting network positions as soon as the gps is turned off - not what I would expect.

(I backed up the database and checked with sqlite whether the data was there.)

Additionally, when I downgrade back to 3.3 (and restore 3.4 data from oandbackup), no data ends up in the app's database at all. Neither when I restore a 3.3 backup consistently (app and data).

Everything is from Fdroid. The system is Lineageos 17.1 with Microg, as from https://download.lineage.microg.org/beryllium/lineage-17.1-20201203-microG-beryllium.zip.

This is not a dupe of #76 - this issue is about data collection once the track is started, that one is about starting the track.

**Comment by bfabiszewski** [comment]
AFAIK On Android 10 and later there is no way to turn off only GPS. 

In earlier versions there was a menu that allowed that. You could choose between "high precision", "battery saving" and "only device" mode. 
Starting from version 10 the menu is gone. Users are only allowed to increase precision by allowing position to be determined from mobile network, wifi and bluetooth devices scanning.
The button in quick access menu is no longer named GPS but Location. Choosing this option disables all location services, not only GPS as before.
As LineageOS 17 is based on Android 10 it is possible that by disabling GPS you are disabling all location services.

You may try to build a development version of the app from github and look into debug log. It will show you which providers are disabled by choosing various user settings.

**Comment by TjrGithub** [comment]
Indeed, I have been disabling all location services with system profiles and/or the quicksettings (while trying to disable GPS only). 
Since upgrading to Android 10, the long time stretches with network-only data have disappeared.

(I wish Android would still allow network-only positions for battery reasons, but that's not going to happen.)
Thanks for looking into this.
