### ISSUE TITLE
Feature request - Update last position without start tracking.

### ISSUE THREAD

**Issue by nexius76** [bfabiszewski/ulogger-android#99]
I think that could be useful have a switch that permit simply only the update of last location instead of adding a point to an unwanted track. In such way ulogger can be used to definitively switch off google sharing location. Would be really great!

In the app should be present a button that simply start the update of device location according with app configiration settings, without start tracking.

Thanks a lot for your great job!

**Comment by bfabiszewski** [comment]
Thanks for this comment.
This is related to the [issue](https://github.com/bfabiszewski/ulogger-server/issues/158) you submitted on server repo, so I am closing it here.
